import test from 'node:test';
import assert from 'node:assert/strict';
import {Match,eye,obstructed,floorAt,moveActor} from './core.mjs';
import {MAPS,pickupWeapon} from './maps.mjs';
import {CHARACTERS,HARNESSES,WEAPONS,validLoadout} from './data.mjs';
const seeded=()=>{let n=17;return()=>((n=(Math.imul(n,1664525)+1013904223)>>>0)/4294967296);};
function fixture(harness='codex',map='crosswire'){const m=new Match('gemini',harness,seeded(),map);m.actors.forEach(a=>{a.protection=0;a.shotWait=0;a.health=0;a.dead=999;});const a=m.actors[0];Object.assign(a,{x:0,z:8,y:0,health:100,armor:0,yaw:0,pitch:0,vx:0,vy:0,vz:0});return [m,a];}
test('expanded roster has unique IDs, full compatibility and five-slot inventories',()=>{assert.equal(CHARACTERS.length,9);assert.equal(HARNESSES.length,7);assert.equal(WEAPONS.length,5);assert.equal(new Set(CHARACTERS.map(c=>c.id)).size,9);for(const c of CHARACTERS)for(const h of HARNESSES){assert.equal(validLoadout(c.id,h.id),c.id!=='claude'||h.id==='claudecode');const m=new Match(c.id,h.id,seeded());assert.equal(m.actors[0].ammo.length,5);assert.equal(new Set(m.actors.map(a=>a.character)).size,5);}});
test('Recompile heals exactly 35, caps at 100 and respects cooldown',()=>{const [m,a]=fixture();a.health=45;assert.ok(m.power(a));assert.equal(a.health,80);assert.equal(m.power(a),false);a.cooldown=0;m.power(a);assert.equal(a.health,100);});
test('Phase Step advances through open space, stops at solid cover and resets',()=>{const [m,a]=fixture('cline');a.x=-11;a.z=8;const before=a.z;m.power(a);assert.ok(before-a.z>5.5);assert.ok(before-a.z<=6);assert.ok(!obstructed(a.x,a.y,a.z,.42,m.arena));a.cooldown=0;a.x=0;a.z=3;m.power(a);assert.ok(a.z>1.1);assert.ok(a.z<3);m.spawn(a);assert.equal(a.active,0);assert.equal(a.cooldown,0);});
test('Context Jam applies only in range and line of sight; slow expires and death clears it',()=>{const [m,a]=fixture('roo');const b=m.actors[1],c=m.actors[2];Object.assign(a,{x:0,z:2});Object.assign(b,{x:2,z:2,y:0,health:100});Object.assign(c,{x:0,z:-2,y:0,health:100});m.power(a);assert.equal(b.slow,3);assert.equal(c.slow,0);const fast={...b,slow:0,vx:0,vz:0,grounded:true,coyote:0,jumpBuffer:0},slow={...fast,slow:3};for(let i=0;i<30;i++){moveActor(fast,{z:1},1/60,m.arena);moveActor(slow,{z:1},1/60,m.arena);}assert.ok(Math.abs(slow.vz)<Math.abs(fast.vz)*.65);b.health=100;b.protection=0;m.damage(b,1000,a);assert.equal(b.slow,0);m.spawn(b);assert.equal(b.slow,0);const [n,p]=fixture('roo');p.slow=.2;for(let i=0;i<20;i++)n.step(1/60);assert.equal(p.slow,0);});
test('Scattergun uses one shell for eight pellet traces and cover blocks them',()=>{const [m,a]=fixture();const b=m.actors[1];Object.assign(b,{x:0,z:5,y:0,health:100,protection:0});a.weapon=3;a.ammo[3]=2;m.fire(a);assert.equal(a.ammo[3],1);assert.equal(m.events.filter(e=>e.type==='shot'&&e.actor===0).length,8);assert.ok(b.health<100&&b.health>=36);a.shotWait=0;Object.assign(a,{x:0,z:3});Object.assign(b,{x:0,z:-3,health:100});m.fire(a);assert.equal(b.health,100);});
test('Plasma Driver travels as a projectile, consumes ammo and damages on impact',()=>{const [m,a]=fixture();const b=m.actors[1];Object.assign(b,{x:0,z:5,y:0,health:100,protection:0});a.weapon=4;a.ammo[4]=2;m.fire(a);assert.equal(m.rockets[0].weapon,4);assert.equal(a.ammo[4],1);assert.equal(b.health,100);for(let i=0;i<6;i++)m.step(1/60);assert.ok(b.health<100);assert.ok(m.events.some(e=>e.type==='explosion'&&e.weapon===4));});
test('all maps have connected navigation, valid supplies, safe spawns and complete bot matches',()=>{for(const map of MAPS){const m=new Match('kimi','roo',seeded(),map.id);const seen=new Set([0]),q=[0];while(q.length)for(const n of m.edges[q.shift()])if(!seen.has(n)){seen.add(n);q.push(n);}assert.equal(seen.size,m.nav.length,map.id);for(const p of [...m.pickups,...m.spawns])assert.equal(obstructed(p.x,p.y,p.z,.42,m.arena),false,`${map.id} ${p.x},${p.z}`);for(const w of [1,2,3,4])assert.ok(m.pickups.some(p=>pickupWeapon(p.kind)===w));for(let i=0;i<18001&&!m.over;i++)m.step(1/60);assert.ok(m.over,map.id);assert.ok(m.stats.kills>10);assert.ok(m.stats.pickups>4);assert.ok(m.stats.powers>2);console.log(map.id,m.time.toFixed(2),m.stats);}});
test('simultaneous matches keep map collision independent and rematch resets new status',()=>{const [a]=fixture('cline','exchange'),[b]=fixture('codex','crosswire');assert.equal(floorAt(0,-12,a.arena),3.8);assert.equal(floorAt(0,-12,b.arena),0);assert.notEqual(a.rayWorld({x:0,y:2,z:5},{x:0,y:0,z:-1},10),b.rayWorld({x:0,y:2,z:5},{x:0,y:0,z:-1},10));a.actors[0].slow=2;a.actors[0].ammo[4]=20;const n=new Match('kimi','roo',seeded(),'foundry');assert.equal(n.arena.id,'foundry');assert.ok(n.actors.every(a=>a.slow===0&&a.ammo[4]===0&&a.cooldown===0));assert.equal(n.rockets.length,0);});
