// One next-generation map per game mode. Each is generated by levelgen.mjs from
// a deterministic seed and a small imperative layout, so the maps share an
// engine but not a silhouette. The legacy maps remain untouched in MAPS.
import {createLevel, mulberry32} from './levelgen.mjs';

const ring = (ctx, x, z, radius, count, place) => {
  for (let i = 0; i < count; i++) { const a = (i / count) * Math.PI * 2; place(ctx, x + Math.cos(a) * radius, z + Math.sin(a) * radius, a, i); }
};
const scatter = (ctx, count, rng, margin, place) => {
  for (let i = 0; i < count; i++) { const x = ctx.bounds.minX + margin + rng() * (ctx.bounds.maxX - ctx.bounds.minX - margin * 2), z = ctx.bounds.minZ + margin + rng() * (ctx.bounds.maxZ - ctx.bounds.minZ - margin * 2); place(ctx, x, z, i); }
};

// 1. Deathmatch — a grand stone colosseum with tiered seating and arches.
const colosseum = createLevel({
  id: 'colosseum', name: 'The Colosseum', tag: 'DEATHMATCH / STONE ARENA', color: '#d8b073', background: '#120e0b', seed: 1101,
  group: 'arena', scale: 'battle', mode: 'deathmatch', size: { w: 84, d: 84 }, biome: 'ruins', amplitude: 1.6, relief: .4,
  description: 'A tiered stone colosseum. Fight across the sand floor, up the ramps, and along the ring of arches.',
  layout(ctx, rng) {
    for (let tier = 0; tier < 4; tier++) {
      const r = 20 + tier * 6.5, h = 1.6 + tier * 1.4;
      ring(ctx, 0, 0, r, 24, (c, x, z, a, i) => {
        if (i % 6 < 2) return; // gaps keep the tiers walkable to bots
        if (i % 3 === 0 && tier < 3) c.addColumn({ x, z, y: c.ground(x, z), radius: .8, height: h + 4 });
        else c.addBlock({ x, z, w: 3.4, d: 3.4, h: c.ground(x, z) + h, kind: 'terrace' });
      });
    }
    for (let i = 0; i < 12; i++) { const a = (i / 12) * Math.PI * 2 + .26; ctx.addArch({ x: Math.cos(a) * 15, z: Math.sin(a) * 15, y: ctx.ground(Math.cos(a) * 15, Math.sin(a) * 15), width: 5.5, height: 6, rot: -a + Math.PI / 2 }); }
    for (let i = -1; i <= 1; i += 2) ctx.addBuilding({ x: i * 15, z: -16, w: 10, d: 8, h: 5, rot: i > 0 ? Math.PI / 2 : -Math.PI / 2, roof: 'flat', door: 'south', floors: 1 });
    scatter(ctx, 8, rng, 12, (c, x, z) => c.addRock({ x, z, scale: .6 + rng() * .5 }));
    ctx.addObjective(0, 0, 5); ctx.addObjective(-22, 0, 3.5); ctx.addObjective(22, 0, 3.5);
    for (let i = 0; i < 8; i++) { const a = (i / 8) * Math.PI * 2; ctx.addSpawn(Math.cos(a) * 9, Math.sin(a) * 9); }
    ctx.addPickup('rocket', -8, 0); ctx.addPickup('rail', 8, 0); ctx.addPickup('scatter', 0, -8); ctx.addPickup('plasma', 0, 8);
    ctx.addPickup('health', -24, 0); ctx.addPickup('health', 24, 0); ctx.addPickup('armor', 0, -24); ctx.addPickup('armor', 0, 24);
  },
});

// 2. Capture the Flag — two snow canyon bases linked by a tunnel and open ridges.
const frostGate = createLevel({
  id: 'frost-gate', name: 'Frost Gate', tag: 'CTF / SNOW CANYON', color: '#a9d8ff', background: '#0b1520', seed: 2202,
  group: 'outdoor', scale: 'warzone', mode: 'ctf', size: { w: 120, d: 80 }, biome: 'snow', amplitude: 8, relief: 2.4,
  description: 'A frozen canyon with walled bases, a central ice tunnel, and ridges that reward a long flank.',
  layout(ctx, rng) {
    ctx.teamSpawns = { 0: [[-38, -16], [-38, 16], [-46, -22], [-46, 22]], 1: [[38, 16], [38, -16], [46, 22], [46, -22]] };
    ctx.flagSpawns = { 0: { x: -48, z: 0 }, 1: { x: 48, z: 0 } };
    ctx.addBuilding({ x: -48, z: 0, w: 16, d: 18, h: 7, rot: Math.PI / 2, roof: 'gable', door: 'east', floors: 1, color: '#cfe8ff' });
    ctx.addBuilding({ x: 48, z: 0, w: 16, d: 18, h: 7, rot: -Math.PI / 2, roof: 'gable', door: 'west', floors: 1, color: '#cfe8ff' });
    ctx.addTunnel([[-38, undefined, 0], [-14, undefined, 0], [14, undefined, 0], [38, undefined, 0]], 3.2);
    ctx.addCavern({ x: 0, z: -20, radius: 13, height: 9 });
    ring(ctx, 0, 0, 26, 10, (c, x, z) => c.addRock({ x, z, scale: 1.4 + rng() * 1.2 }));
    scatter(ctx, 22, rng, 8, (c, x, z) => (rng() > .45 ? c.addTree({ x, z, scale: .9 + rng() * .6 }) : c.addRock({ x, z, scale: .7 + rng() * .6 })));
    ctx.addObjective(-30, 0, 3.5); ctx.addObjective(0, 0, 4); ctx.addObjective(30, 0, 3.5);
    ctx.addPickup('rail', 0, 22); ctx.addPickup('rocket', -18, -18); ctx.addPickup('rocket', 18, 18); ctx.addPickup('health', -48, 12); ctx.addPickup('health', 48, -12); ctx.addPickup('armor', 0, -20);
  },
});

// 3. King of the Hill — a grassy mesa with a cavern beneath and ramps to the top.
const sunkenHill = createLevel({
  id: 'sunken-hill', name: 'Sunken Hill', tag: 'KOTH / TERRAIN HILL', color: '#8fd08a', background: '#0a1410', seed: 3303,
  group: 'outdoor', scale: 'battle', mode: 'koth', size: { w: 100, d: 100 }, biome: 'forest', amplitude: 6, relief: 1.5,
  description: 'A rounded hill dominates the field. Hold the crown, or fight through the cavern that runs beneath it.',
  layout(ctx, rng) {
    ctx.teamSpawns = { 0: [[-38, -6], [-38, 6], [-30, -22], [-30, 22]], 1: [[38, 6], [38, -6], [30, 22], [30, -22]] };
    ctx.flagSpawns = { 0: { x: -38, z: 0 }, 1: { x: 38, z: 0 } };
    ctx.addCavern({ x: 0, z: 0, radius: 15, height: 10 });
    ring(ctx, 0, 0, 30, 8, (c, x, z, a) => c.addBridge({ x, z, y: c.ground(x, z) + (a < Math.PI ? 0 : 2), w: 10, d: 4, rot: -a, thickness: .5 }));
    scatter(ctx, 26, rng, 8, (c, x, z) => c.addTree({ x, z, scale: .8 + rng() * .8 }));
    for (let i = 0; i < 6; i++) { const a = (i / 6) * Math.PI * 2 + .4; ctx.addRock({ x: Math.cos(a) * 14, z: Math.sin(a) * 14, scale: 1.3 }); }
    ctx.addObjective(0, 0, 6); ctx.addObjective(-28, 0, 4); ctx.addObjective(28, 0, 4);
    for (let i = 0; i < 8; i++) { const a = (i / 8) * Math.PI * 2; ctx.addSpawn(Math.cos(a) * 38, Math.sin(a) * 38); }
    ctx.addPickup('rail', 0, -34); ctx.addPickup('rocket', 0, 34); ctx.addPickup('health', -34, 0); ctx.addPickup('health', 34, 0); ctx.addPickup('armor', -18, -18); ctx.addPickup('armor', 18, 18);
  },
});

// 4. Domination — a riverside town of enterable buildings around three plazas.
const riverbend = createLevel({
  id: 'riverbend', name: 'Riverbend', tag: 'DOMINATION / TOWN', color: '#e0b06a', background: '#131009', seed: 4404,
  group: 'urban', scale: 'warzone', mode: 'domination', size: { w: 110, d: 90 }, biome: 'urban', amplitude: 4, relief: 1.2,
  description: 'A low river valley town. Three plazas sit between walkable buildings and a flooded centre channel.',
  layout(ctx, rng) {
    ctx.teamSpawns = { 0: [[-44, -22], [-44, 22], [-36, -18]], 1: [[44, 22], [44, -22], [36, 18]] };
    const towns = [[-34, 0, 12, 10], [-14, -26, 10, 9], [14, 26, 10, 9], [34, 0, 12, 10], [-4, 0, 9, 8], [12, -6, 8, 8], [-16, 10, 8, 8]];
    for (const [x, z, w, d] of towns) ctx.addBuilding({ x, z, w, d, h: 5.5, rot: rng() > .5 ? 0 : Math.PI / 2, roof: 'gable', door: rng() > .5 ? 'south' : 'west', floors: 1 });
    ctx.addTunnel([[-46, undefined, 0], [-20, undefined, 0], [20, undefined, 0], [46, undefined, 0]], 3);
    scatter(ctx, 14, rng, 10, (c, x, z) => c.addCrate({ x, z, scale: .8 + rng() * .5 }));
    ctx.addObjective(-30, 0, 5); ctx.addObjective(0, 0, 5); ctx.addObjective(30, 0, 5);
    ctx.addPickup('rocket', 0, -30); ctx.addPickup('rocket', 0, 30); ctx.addPickup('rail', -30, -20); ctx.addPickup('rail', 30, 20); ctx.addPickup('health', -8, 0); ctx.addPickup('armor', 8, 0);
  },
});

// 5. Assault — a hill fortress the attackers breach sector by sector.
const fortress = createLevel({
  id: 'fortress', name: 'Iron Fortress', tag: 'ASSAULT / FORTRESS', color: '#c88a5a', background: '#15100c', seed: 5505,
  group: 'indoor', scale: 'warzone', mode: 'assault', size: { w: 110, d: 80 }, biome: 'ruins', amplitude: 7, relief: 2,
  description: 'Attackers cross open ground, breach the outer wall, then fight through a tunnel into the keep.',
  layout(ctx, rng) {
    ctx.teamSpawns = { 0: [[-46, -20], [-46, 0], [-46, 20], [-40, 10]], 1: [[34, -16], [34, 16], [40, 0], [26, 0]] };
    ctx.addBuilding({ x: -34, z: 0, w: 14, d: 12, h: 5, roof: 'flat', door: 'east', floors: 1 });
    ctx.addBuilding({ x: 30, z: 0, w: 26, d: 40, h: 10, roof: 'flat', door: 'west', doorWidth: 4, floors: 1 });
    ctx.addTunnel([[-16, undefined, -14], [6, undefined, -14], [18, undefined, -6]], 2.8);
    ctx.addTunnel([[-16, undefined, 14], [6, undefined, 14], [18, undefined, 6]], 2.8);
    for (let i = -2; i <= 2; i++) { ctx.addColumn({ x: i * 12, z: -28, radius: .7, height: 6 }); ctx.addColumn({ x: i * 12, z: 28, radius: .7, height: 6 }); }
    scatter(ctx, 10, rng, 12, (c, x, z) => c.addRock({ x, z, scale: .8 + rng() * .6 }));
    ctx.addObjective(-10, 0, 4); ctx.addObjective(12, 0, 4); ctx.addObjective(30, 0, 5);
    ctx.addPickup('rocket', -20, 0); ctx.addPickup('rail', 12, -20); ctx.addPickup('rail', 12, 20); ctx.addPickup('health', -30, -20); ctx.addPickup('armor', 30, 0);
  },
});

// 6. Team Deathmatch — an indoor plaza with a central atrium and side rooms.
const atrium = createLevel({
  id: 'atrium', name: 'The Atrium', tag: 'TEAM / INDOOR PLAZA', color: '#7fd8e6', background: '#0a1216', seed: 6606,
  group: 'indoor', scale: 'battle', mode: 'teamdeathmatch', size: { w: 90, d: 90 }, biome: 'urban', amplitude: 2, relief: .6,
  description: 'A two-level corporate atrium. Side rooms, a mezzanine ring, and a glass centre make every lane contested.',
  layout(ctx, rng) {
    ctx.teamSpawns = { 0: [[-38, -34], [-38, -20], [-30, -34]], 1: [[38, 34], [38, 20], [30, 34]] };
    for (const [x, z, rot] of [[-30, -20, 0], [30, 20, 0], [-20, 30, Math.PI / 2], [20, -30, Math.PI / 2], [0, -34, 0], [0, 34, Math.PI]]) ctx.addBuilding({ x, z, w: 14, d: 12, h: 5, rot, roof: 'flat', door: 'south', floors: 1 });
    ring(ctx, 0, 0, 16, 8, (c, x, z) => c.addColumn({ x, z, radius: .8, height: 7 }));
    ctx.addBridge({ x: 0, z: -10, y: 4, w: 22, d: 3, rot: 0, thickness: .5 });
    ctx.addBridge({ x: 0, z: 10, y: 4, w: 22, d: 3, rot: 0, thickness: .5 });
    scatter(ctx, 12, rng, 10, (c, x, z) => c.addCrate({ x, z, scale: .8 + rng() * .4 }));
    ctx.addObjective(-20, 0, 4); ctx.addObjective(0, 0, 4); ctx.addObjective(20, 0, 4);
    ctx.addPickup('rocket', 0, -22); ctx.addPickup('rocket', 0, 22); ctx.addPickup('rail', -22, 0); ctx.addPickup('rail', 22, 0); ctx.addPickup('health', -30, 0); ctx.addPickup('armor', 30, 0);
  },
});

// 7. Instagib — a catacomb of narrow tunnels and crypt chambers.
const catacombs = createLevel({
  id: 'catacombs', name: 'The Catacombs', tag: 'INSTAGIB / TUNNELS', color: '#b79bff', background: '#0b0a12', seed: 7707,
  group: 'indoor', scale: 'battle', mode: 'instagib', size: { w: 90, d: 90 }, biome: 'cavern', amplitude: 3, relief: 1,
  description: 'A tight underground network. Every tunnel is a rail lane and every chamber is a trap.',
  layout(ctx, rng) {
    const hubs = [[-26, -26], [26, -26], [26, 26], [-26, 26], [0, 0]];
    for (const [x, z] of hubs) ctx.addCavern({ x, z, radius: 10, height: 7 });
    for (let i = 0; i < hubs.length; i++) for (let j = i + 1; j < hubs.length; j++) { if ((i + j) % 2) continue; ctx.addTunnel([[hubs[i][0], undefined, hubs[i][1]], [hubs[j][0], undefined, hubs[j][1]]], 2.4); }
    scatter(ctx, 16, rng, 8, (c, x, z) => c.addRuin({ x, z, scale: .7 + rng() * .6 }));
    ctx.addObjective(0, 0, 4); ctx.addObjective(-26, -26, 3.5); ctx.addObjective(26, 26, 3.5);
    for (const [x, z] of [[-40, 0], [40, 0], [0, -40], [0, 40], [-40, -40], [40, -40], [-40, 40], [40, 40]]) ctx.addSpawn(x, z);
    ctx.addPickup('rail', -26, 0); ctx.addPickup('rail', 26, 0); ctx.addPickup('rail', 0, -26); ctx.addPickup('rail', 0, 26); ctx.addPickup('health', 0, 0);
  },
});

// 8. Rocket Arena — a volcanic slagworks of catwalks and lava-lit furnaces.
const slagworks = createLevel({
  id: 'slagworks', name: 'Slagworks', tag: 'ROCKETS / VOLCANIC', color: '#ff7a4d', background: '#160b07', seed: 8808,
  group: 'urban', scale: 'battle', mode: 'rockets', size: { w: 90, d: 80 }, biome: 'volcanic', amplitude: 5, relief: 1.6,
  description: 'A molten foundry. Elevated catwalks cross the slag pits and rocket duels decide every crossing.',
  layout(ctx, rng) {
    for (const [x, z] of [[-22, -14], [22, 14], [-22, 14], [22, -14]]) ctx.addBuilding({ x, z, w: 12, d: 10, h: 6, roof: 'flat', door: 'south', floors: 1 });
    ctx.addBridge({ x: 0, z: 0, y: 5, w: 44, d: 4, rot: 0, thickness: .5 });
    ctx.addBridge({ x: 0, z: 0, y: 5, w: 40, d: 4, rot: Math.PI / 2, thickness: .5 });
    ring(ctx, 0, 0, 9, 6, (c, x, z) => c.addRock({ x, z, scale: 1.2 }));
    scatter(ctx, 14, rng, 10, (c, x, z) => c.addBarrel({ x, z, scale: .9 + rng() * .4 }));
    ctx.addObjective(-24, 0, 3.5); ctx.addObjective(0, 0, 4); ctx.addObjective(24, 0, 3.5);
    ctx.addPickup('rocket', -30, -20); ctx.addPickup('rocket', 30, 20); ctx.addPickup('rocket', 0, -30); ctx.addPickup('rocket', 0, 30); ctx.addPickup('health', -12, 0); ctx.addPickup('armor', 12, 0);
  },
});

// 9. Full Arsenal — a compact forge arena, all weapons live.
const forge = createLevel({
  id: 'forge', name: 'The Forge', tag: 'ARSENAL / COMPACT', color: '#ffd166', background: '#130f0a', seed: 9909,
  group: 'arena', scale: 'battle', mode: 'arsenal', size: { w: 80, d: 80 }, biome: 'urban', amplitude: 1.2, relief: .3,
  description: 'A close forge floor with a raised centre and side workshops. Every weapon, one killbox.',
  layout(ctx, rng) {
    ring(ctx, 0, 0, 16, 6, (c, x, z) => c.addColumn({ x, z, radius: .8, height: 5 }));
    ctx.addBridge({ x: 0, z: 0, y: 2.2, w: 11, d: 11, rot: 0, thickness: .5 });
    for (const [x, z, rot] of [[-26, -26, -Math.PI / 2], [26, 26, Math.PI / 2], [-26, 26, Math.PI], [26, -26, 0]]) ctx.addBuilding({ x, z, w: 12, d: 10, h: 5, rot, roof: 'gable', door: 'south', floors: 1 });
    scatter(ctx, 10, rng, 8, (c, x, z) => c.addCrate({ x, z, scale: .8 }));
    ctx.addObjective(0, 0, 4); ctx.addObjective(-24, 0, 3.5); ctx.addObjective(24, 0, 3.5);
    for (let i = 0; i < 8; i++) { const a = (i / 8) * Math.PI * 2; ctx.addSpawn(Math.cos(a) * 32, Math.sin(a) * 32); }
    ctx.addPickup('rocket', -10, 0); ctx.addPickup('rail', 10, 0); ctx.addPickup('plasma', 0, -10); ctx.addPickup('scatter', 0, 10); ctx.addPickup('health', -26, 0); ctx.addPickup('armor', 26, 0);
  },
});

// 10. Combined Arms — a wide valley with terrain, bunkers, a tunnel and armour.
const titanValley = createLevel({
  id: 'titan-valley', name: 'Titan Valley', tag: 'COMBINED ARMS / VALLEY', color: '#8fb0c7', background: '#0d1622', seed: 1010,
  group: 'combined', scale: 'warzone', mode: 'combined-arms', size: { w: 150, d: 110 }, biome: 'forest', amplitude: 12, relief: 3.2, step: 8,
  description: 'A vast mixed-arms basin: rolling terrain, fortified bunkers, a central tunnel and armour lanes for Pumas and Hornets.',
  layout(ctx, rng) {
    ctx.teamSpawns = { 0: [[-60, -20], [-60, 0], [-60, 20], [-50, 34], [-50, -34]], 1: [[60, -20], [60, 0], [60, 20], [50, 34], [50, -34]] };
    ctx.addBuilding({ x: -60, z: 0, w: 20, d: 24, h: 8, rot: Math.PI / 2, roof: 'flat', door: 'east', doorWidth: 3.4, floors: 1 });
    ctx.addBuilding({ x: 60, z: 0, w: 20, d: 24, h: 8, rot: -Math.PI / 2, roof: 'flat', door: 'west', doorWidth: 3.4, floors: 1 });
    for (const [x, z] of [[-28, -30], [28, 30], [-28, 30], [28, -30]]) { ctx.addBuilding({ x, z, w: 12, d: 12, h: 4.5, roof: 'flat', door: 'south', floors: 1 }); ctx.addRock({ x: x + 8, z: z + 8, scale: 1.6 }); }
    ctx.addTunnel([[-46, undefined, 0], [-18, undefined, 0], [0, undefined, 6], [18, undefined, 0], [46, undefined, 0]], 3.4);
    ctx.addCavern({ x: 0, z: -30, radius: 12, height: 11 });
    ctx.addCavern({ x: 0, z: 30, radius: 12, height: 11 });
    scatter(ctx, 34, rng, 7, (c, x, z) => (Math.abs(x) > 18 ? c.addTree({ x, z, scale: .8 + rng() * .7 }) : c.addRock({ x, z, scale: .8 + rng() * .9 })));
    ctx.addObjective(0, 0, 6); ctx.addObjective(-34, -26, 4); ctx.addObjective(34, 26, 4);
    ctx.addVehicle({ kind: 'puma', x: -34, z: 34, yaw: 0 }); ctx.addVehicle({ kind: 'puma', x: 34, z: -34, yaw: Math.PI }); ctx.addVehicle({ kind: 'puma', x: 0, z: 40, yaw: Math.PI }); ctx.addVehicle({ kind: 'puma', x: 0, z: -40, yaw: 0 });
    ctx.addVehicle({ kind: 'hornet', x: -50, z: -40, yaw: 0 }); ctx.addVehicle({ kind: 'hornet', x: 50, z: 40, yaw: Math.PI });
    ctx.addPickup('rocket', 0, -24); ctx.addPickup('rocket', 0, 24); ctx.addPickup('rail', -34, 0); ctx.addPickup('rail', 34, 0); ctx.addPickup('health', -60, 30); ctx.addPickup('health', 60, -30); ctx.addPickup('armor', 0, 0);
  },
});

// 11. Payload — a long industrial convoy route from a western depot to an eastern fuel yard.
const convoyLine = createLevel({
  id: 'convoy-line', name: 'Convoy Line', tag: 'PAYLOAD / CONVOY ROUTE', color: '#e0b06a', background: '#100c07', seed: 1111,
  group: 'urban', scale: 'warzone', mode: 'payload', size: { w: 152, d: 72 }, biome: 'urban', amplitude: 3, relief: 1.1,
  description: 'A long industrial convoy route. Attackers push the cart from a western depot, across a central bridge and tunnel, to the eastern fuel yard.',
  layout(ctx, rng) {
    ctx.teamSpawns = { 0: [[-66, -12], [-66, 12], [-72, -24], [-72, 24]], 1: [[66, 12], [66, -12], [72, 24], [72, -24]] };
    ctx.addBuilding({ x: -64, z: 0, w: 18, d: 18, h: 6, rot: Math.PI / 2, roof: 'flat', door: 'east', doorWidth: 3.4, floors: 1 });
    ctx.addBuilding({ x: 64, z: 0, w: 18, d: 18, h: 7, rot: -Math.PI / 2, roof: 'gable', door: 'west', doorWidth: 3.4, floors: 1 });
    for (const [x, z] of [[-36, -20], [-36, 20], [-8, -24], [-8, 24], [22, -20], [22, 20], [46, -22], [46, 22]]) ctx.addBuilding({ x, z, w: 11, d: 9, h: 5, rot: rng() > .5 ? 0 : Math.PI / 2, roof: 'flat', door: rng() > .5 ? 'south' : 'north', floors: 1 });
    ctx.addTunnel([[-48, undefined, 0], [-18, undefined, 0], [18, undefined, 0], [48, undefined, 0]], 3.2);
    ctx.addBridge({ x: 0, z: 0, y: ctx.ground(0, 0) + 1.4, w: 16, d: 10, rot: 0, thickness: .5 });
    scatter(ctx, 18, rng, 8, (c, x, z) => (rng() > .5 ? c.addCrate({ x, z, scale: .8 + rng() * .5 }) : c.addRock({ x, z, scale: .7 + rng() * .6 })));
    ctx.addObjective(-32, 0, 4); ctx.addObjective(0, 0, 5); ctx.addObjective(34, 0, 4);
    ctx.addVehicle({ kind: 'puma', x: -52, z: 26, yaw: 0 }); ctx.addVehicle({ kind: 'puma', x: 52, z: -26, yaw: Math.PI });
    ctx.addPickup('rocket', -18, 0); ctx.addPickup('rail', 18, 0); ctx.addPickup('scatter', 0, -15); ctx.addPickup('plasma', 0, 15);
    ctx.addPickup('health', -58, 0); ctx.addPickup('health', 58, 0); ctx.addPickup('armor', 0, -22); ctx.addPickup('armor', 0, 22);
  },
});

export const NEXTGEN_MAPS = [colosseum, frostGate, sunkenHill, riverbend, fortress, atrium, catacombs, slagworks, forge, titanValley, convoyLine];
