import * as T from 'three';
import {SoftwareRenderer} from './software.mjs';
import {CHARACTERS,WEAPONS} from './data.mjs';
import {aim} from './core.mjs';
import {MAPS,pickupWeapon} from './maps.mjs';
const V=(x=0,y=0,z=0)=>new T.Vector3(x,y,z);
const material=(color,metal=.5,rough=.42,emissive=false)=>new T.MeshStandardMaterial({color,metalness:metal,roughness:rough,...(emissive?{emissive:color,emissiveIntensity:1.6}:{})});
function box(parent,w,h,d,x,y,z,mat){const m=new T.Mesh(new T.BoxGeometry(w,h,d),mat);m.position.set(x,y,z);parent.add(m);return m;}
function cylinder(parent,r1,r2,h,x,y,z,mat,segments=12){const m=new T.Mesh(new T.CylinderGeometry(r1,r2,h,segments),mat);m.position.set(x,y,z);parent.add(m);return m;}
function ring(parent,r,t,x,y,z,mat,rx=Math.PI/2){const m=new T.Mesh(new T.TorusGeometry(r,t,6,32),mat);m.position.set(x,y,z);m.rotation.x=rx;parent.add(m);return m;}
export function weaponModel(type=0){const g=new T.Group(),dark=material('#222f37'),light=material('#73848a'),glow=material(WEAPONS[type].color,.3,.3,true);g.userData.type=type;
 if(type===0){box(g,.2,.23,.62,0,0,-.15,dark);box(g,.24,.1,.34,0,.16,-.18,light);box(g,.07,.045,.48,.105,.06,-.2,glow);const barrel=cylinder(g,.07,.07,.5,0,.01,-.6,light);barrel.rotation.x=Math.PI/2;box(g,.09,.17,.12,0,.25,-.03,dark);box(g,.09,.2,.14,0,-.19,.03,dark);}
 if(type===1){const barrel=cylinder(g,.22,.24,.9,0,0,-.25,dark);barrel.rotation.x=Math.PI/2;ring(g,.205,.037,0,0,-.72,glow,0);box(g,.3,.09,.55,0,.23,-.15,light);box(g,.15,.25,.19,0,-.26,.02,light);for(const x of [-.24,.24])box(g,.04,.24,.38,x,0,-.25,glow);}
 if(type===2){box(g,.21,.22,.7,0,0,-.26,dark);for(const x of [-.14,.14]){box(g,.075,.1,.92,x,.025,-.58,light);box(g,.035,.045,.8,x,.085,-.58,glow);}box(g,.15,.08,.25,0,.2,-.17,glow);box(g,.08,.2,.13,0,-.2,0,dark);}
 if(type===3){box(g,.36,.22,.5,0,0,-.1,dark);for(const x of [-.12,.12]){const barrel=cylinder(g,.095,.095,.58,x,.03,-.51,light);barrel.rotation.x=Math.PI/2;ring(g,.075,.017,x,.03,-.81,glow,0);}box(g,.32,.1,.25,0,-.13,-.32,glow);box(g,.12,.24,.13,0,-.22,.09,dark);}
 if(type===4){box(g,.23,.24,.62,0,0,-.2,dark);for(const z of [-.25,-.45,-.65])ring(g,.17,.025,0,0,z,glow,0);const core=new T.Mesh(new T.IcosahedronGeometry(.12,1),glow);core.position.z=-.67;g.add(core);for(const x of [-.18,.18])box(g,.08,.14,.7,x,0,-.3,light);box(g,.13,.22,.15,0,-.21,.05,dark);}
 const flash=new T.Mesh(new T.SphereGeometry(.12,6,4),new T.MeshBasicMaterial({color:WEAPONS[type].color}));flash.position.set(0,0,type===2?-1.05:-.83);flash.visible=false;g.add(flash);g.userData.flash=flash;return g;}
export function robotModel(id){const c=CHARACTERS.find(c=>c.id===id)||CHARACTERS[0],g=new T.Group(),armor=material(c.accent,.72,.32),color=material(c.color,.65,.3),dark=material('#17252b'),glow=material(c.color,.4,.2,true);
 const torso=box(g,.65,.6,.36,0,1.05,0,armor);box(g,.43,.26,.08,0,1.1,-.215,dark);box(g,.22,.055,.09,0,1.13,-.27,glow);box(g,.4,.16,.3,0,.66,0,dark);
 const head=new T.Group();head.position.set(0,1.56,0);g.add(head);
 if(id==='chatgpt'){const helmet=new T.Mesh(new T.IcosahedronGeometry(.28,1),armor);helmet.scale.set(1,.9,.88);head.add(helmet);ring(head,.16,.022,0,0,-.225,color,0);ring(head,.11,.017,0,0,-.238,glow,0);}
 else{box(head,.44,.36,.37,0,0,0,armor);box(head,.36,.07,.06,0,.01,-.2,glow);}
 if(id==='claude'){for(const x of [-.31,.31]){const fin=box(head,.09,.3,.24,x,.03,0,color);fin.rotation.z=x*-.5;}box(g,.12,.32,.1,0,1.08,-.26,color);}
 if(id==='grok'){box(head,.06,.34,.07,.22,.29,0,color);box(head,.14,.12,.12,-.17,.13,-.2,dark);box(g,.8,.15,.42,0,1.3,0,color);}
 if(id==='meta'){for(const x of [-.15,.15])ring(g,.17,.033,x,1.08,-.26,glow,0);}
 if(id==='qwen'){for(let i=0;i<3;i++)box(g,.67-i*.1,.07,.46,0,1.23-i*.13,0,color);const crown=box(head,.4,.12,.25,0,.24,0,color);crown.rotation.z=.15;}
 if(id==='gemini'){for(const x of [-.14,.14]){const star=new T.Mesh(new T.OctahedronGeometry(.13),glow);star.position.set(x,.04,-.24);head.add(star);}box(g,.04,.55,.08,0,1.05,-.25,color);}
 if(id==='deepseek'){const crest=box(head,.07,.35,.34,0,.23,.02,color);crest.rotation.z=-.15;for(const x of [-.33,.33])box(g,.09,.36,.48,x,1.1,0,color);}
 if(id==='mistral'){for(let i=0;i<3;i++){const fin=box(head,.14,.12,.15,.15-i*.15,.28+i*.05,0,color);fin.rotation.z=.2;}for(let i=0;i<3;i++)box(g,.48,.04,.05,0,.95+i*.12,-.25,glow);}
 if(id==='kimi'){ring(head,.32,.032,0,.03,0,glow,Math.PI/3);box(g,.13,.42,.06,-.18,1.03,-.23,color);box(g,.13,.42,.06,.18,1.03,-.23,color);}
 const limbs=[];for(const side of [-1,1]){const arm=new T.Group();arm.position.set(side*.45,1.28,0);g.add(arm);box(arm,.22,.2,.3,0,-.02,0,color);box(arm,.16,.4,.19,0,-.28,0,dark);box(arm,.19,.18,.21,0,-.48,-.035,armor);limbs.push(arm);
 const leg=new T.Group();leg.position.set(side*.2,.65,0);g.add(leg);box(leg,.24,.36,.27,0,-.15,0,armor);box(leg,.17,.27,.18,0,-.44,0,dark);box(leg,.26,.15,.39,0,-.61,-.07,color);box(leg,.08,.18,.03,0,-.37,-.13,glow);limbs.push(leg);}
 const gunAnchor=new T.Group();gunAnchor.position.set(.44,.84,-.12);g.add(gunAnchor);const weapon=weaponModel(0);weapon.scale.setScalar(.7);gunAnchor.add(weapon);
 const shield=new T.Mesh(new T.SphereGeometry(1.15,16,12),new T.MeshBasicMaterial({color:c.color,transparent:true,opacity:.13,wireframe:true}));shield.scale.set(.7,1,.7);shield.position.y=.9;g.add(shield);shield.visible=false;
 const base=new T.Mesh(new T.RingGeometry(.47,.54,28),new T.MeshBasicMaterial({color:c.color,side:T.DoubleSide,transparent:true,opacity:.7}));base.rotation.x=-Math.PI/2;base.position.y=.02;g.add(base);
 g.userData={limbs,head,torso,gunAnchor,weapon,shield,color:c.color};return g;}
function textLabel(parent,text,x,y,z,size=1,color='#8ad9d3',ry=0){const canvas=document.createElement('canvas');canvas.width=512;canvas.height=128;const ctx=canvas.getContext('2d');ctx.font='bold 78px monospace';ctx.textAlign='center';ctx.fillStyle=color;ctx.fillText(text,256,90);const tex=new T.CanvasTexture(canvas);const m=new T.Mesh(new T.PlaneGeometry(size*4,size),new T.MeshBasicMaterial({map:tex,transparent:true,depthWrite:false}));m.position.set(x,y,z);m.rotation.y=ry;m.userData.label=text;m.userData.labelSize=size*.6;parent.add(m);return m;}
export class ArenaView{
 constructor(canvas){const context=canvas.getContext('webgl2',{antialias:true,alpha:false});this.renderer=context?new T.WebGLRenderer({canvas,context,antialias:true,alpha:false,powerPreference:'high-performance'}):new SoftwareRenderer(canvas);this.renderer.setPixelRatio(Math.min(window.devicePixelRatio,1.5));this.renderer.outputColorSpace=T.SRGBColorSpace;this.renderer.toneMapping=T.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1.2;
 this.scene=new T.Scene();this.scene.background=new T.Color('#090f17');this.scene.fog=new T.FogExp2('#090f17',.018);this.camera=new T.PerspectiveCamera(82,1,.08,120);this.camera.rotation.order='YXZ';this.scene.add(new T.HemisphereLight('#b2eeff','#1f252c',2));const sun=new T.DirectionalLight('#c9e5ef',2.8);sun.position.set(3,12,8);this.scene.add(sun);
   this.buildArena();this.actorModels=new Map();this.pickupModels=[];this.rocketModels=new Map();this.effects=[];this.lastEvent=0;this.flashUntil=0;this.playerId=0;this.spectator=false;this.hands=new T.Group();this.camera.add(this.hands);this.scene.add(this.camera);this.currentWeapon=-1;this.menu=this.makeMenu();this.resize();}
   setDisplay(prefs){this.camera.fov=prefs.fov;this.camera.updateProjectionMatrix();this.showWeapon=prefs.showWeapon;}
   setPlayerId(id){this.playerId=id;}
   setSpectator(on){this.spectator=on===true;}
  resize(){const w=this.renderer.domElement.clientWidth,h=this.renderer.domElement.clientHeight;this.renderer.setSize(w,h,false);this.camera.aspect=w/h;this.camera.updateProjectionMatrix();this.menu.camera.aspect=w/h;this.menu.camera.updateProjectionMatrix();}
 buildArena(arena=MAPS[0]){if(this.worldGroup){this.scene.remove(this.worldGroup);this.disposeObject(this.worldGroup);}this.mapId=arena.id;const world=new T.Group();this.worldGroup=world;this.scene.add(world);this.scene.background=new T.Color(arena.background);this.scene.fog=new T.FogExp2(arena.background,.018);
 const floor=material(arena.id==='foundry'?'#382c26':'#23313b',.65,.52),wall=material(arena.id==='crosswire'?'#25233e':'#19262f',.68,.5),trim=material('#45606a'),glow=material(arena.color,.4,.3,true);
 // Subdivide the floor: smaller surfaces also improve the software renderer's depth ordering.
 for(let x=-12.5;x<=12.5;x+=5)for(let z=-12.5;z<=12.5;z+=5)box(world,5,.5,5,x,-.25,z,floor);
 const grid=new T.GridHelper(28,14,arena.color,'#304752');grid.position.y=.006;world.add(grid);
 for(const b of arena.blocks){box(world,b.w,b.h,b.d,b.x,b.h/2,b.z,b.kind==='reactor'?material('#2f4249'):wall);
 if(b.kind==='cover'){box(world,b.w+.03,.055,b.d+.03,b.x,b.h-.15,b.z,glow);box(world,b.w-.3,.4,.04,b.x,b.h*.5,b.z+b.d/2+.01,trim);}
 if(b.kind==='reactor'){for(const y of [.3,2.8,b.h+.06]){const rim=box(world,b.w+.08,.055,b.d+.08,b.x,y,b.z,glow);}for(const x of [-b.w*.32,b.w*.32])box(world,.055,b.h-.5,.045,b.x+x,b.h/2,b.z+b.d/2+.02,glow);}
 if(b.kind==='wall')for(let j=-12;j<=12;j+=4){const x=b.w>5?j:b.x,z=b.d>5?j:b.z;box(world,b.w>5?.25:1.1,8,b.d>5?.25:1.1,x,4,z,trim);}}
 if(arena.raised){for(const x of [-11.05,11.05]){const length=Math.hypot(12,3.8),ramp=box(world,5.5,.18,length,x,1.83,-3,floor);ramp.rotation.x=Math.atan(3.8/12);for(const sx of [-2.2,2.2]){const strip=box(world,.06,.04,length,x+sx,1.96,-3,glow);strip.rotation.x=Math.atan(3.8/12);}}box(world,27,.06,.07,0,3.84,-9,glow);}
 if(arena.id==='crosswire'){for(const x of [-1.6,1.6])box(world,.055,.03,26,x,.04,0,glow);for(const z of [-1.6,1.6])box(world,26,.03,.055,0,.04,z,glow);ring(world,2,.025,0,6.2,0,glow);}
 if(arena.id==='exchange')for(const y of [.25,3.5,5.5])ring(world,2.1,.055,0,y,0,glow);
 if(arena.id==='foundry')for(const x of [-4,4]){for(const z of [-2,0,2])box(world,1.8,.03,.35,x,5.77,z,glow);textLabel(world,'HOT',x,4,2.52,.35,'#ffc684');}
 textLabel(world,arena.name.toUpperCase(),0,6.5,-13.94,1.3);textLabel(world,'02',-13.93,5.8,-2,1.2,arena.color,Math.PI/2);textLabel(world,'01',13.93,5.8,4,1.2,arena.color,-Math.PI/2);
 for(const x of [-7,7])box(world,.07,.04,23,x,.06,1,glow);
 for(const z of [-10,0,10]){box(world,28,.3,.35,0,8.5,z,trim);box(world,20,.05,.15,0,8.32,z,glow);}
 for(const x of [-12,12]){const light=new T.PointLight(arena.color,28,15,2);light.position.set(x,5,0);world.add(light);}
 }
 makeMenu(){const scene=new T.Scene();scene.background=new T.Color('#080f13');scene.fog=new T.FogExp2('#080f13',.055);const camera=new T.PerspectiveCamera(38,1,.1,80);camera.position.set(5,3.3,10);camera.lookAt(0,1.4,0);scene.add(new T.HemisphereLight('#bdedee','#233139',2.8));const key=new T.DirectionalLight('#e4fff3',4);key.position.set(-4,6,5);scene.add(key);const rim=new T.PointLight('#52e5cf',80,15);rim.position.set(3,3,-3);scene.add(rim);
 const dark=material('#152128',.8,.4),glow=material('#67e7d3',.4,.2,true);box(scene,50,.3,50,0,-.35,0,dark);const grid=new T.GridHelper(40,40,'#284443','#192c31');grid.position.y=-.19;scene.add(grid);cylinder(scene,1.55,1.8,.3,0,-.02,0,dark,48);ring(scene,1.57,.018,0,.15,0,glow);ring(scene,2.05,.014,0,-.16,0,glow);ring(scene,2.2,.01,0,-.16,0,glow);
 for(let i=-4;i<=4;i++){box(scene,.25,9,.5,i*3,4,-6,dark);box(scene,.045,6,.04,i*3+.18,4,-5.72,glow);}
 const model=robotModel('chatgpt');model.scale.setScalar(2.15);model.position.y=.17;model.rotation.y=.25;scene.add(model);return {scene,camera,model,id:'chatgpt'};}
 setCharacter(id){if(id===this.menu.id)return;this.disposeObject(this.menu.model);this.menu.scene.remove(this.menu.model);this.menu.model=robotModel(id);this.menu.model.scale.setScalar(2.15);this.menu.model.position.y=.17;this.menu.scene.add(this.menu.model);this.menu.id=id;}
  setMatch(match){if(this.mapId!==match.arena.id)this.buildArena(match.arena);for(const m of [...this.actorModels.values(),...this.pickupModels]){this.scene.remove(m);this.disposeObject(m);}this.actorModels=new Map(match.actors.map(a=>{const m=robotModel(a.character);this.scene.add(m);return [a.id,m];}));this.pickupModels=match.pickups.map(p=>{const g=new T.Group(),colors={health:'#77efba',armor:'#6dbfff',rocket:'#ffb164',rail:'#bf9cff',scatter:'#ffde87',plasma:'#72cfff'},mat=material(colors[p.kind],.4,.3,true);if(p.kind==='health'){box(g,.6,.19,.19,0,.65,0,mat);box(g,.19,.6,.19,0,.65,0,mat);}else if(p.kind==='armor'){const m=new T.Mesh(new T.OctahedronGeometry(.4),mat);m.position.y=.7;g.add(m);}else{const w=weaponModel(pickupWeapon(p.kind));w.position.y=.75;w.scale.setScalar(.7);g.add(w);}ring(g,.55,.022,0,.07,0,mat);g.position.set(p.x,p.y,p.z);this.scene.add(g);return g;});for(const e of this.effects){this.scene.remove(e.obj);this.disposeObject(e.obj);}this.effects=[];for(const m of this.rocketModels.values()){this.scene.remove(m);this.disposeObject(m);}this.rocketModels.clear();this.lastEvent=match.serial;this.currentWeapon=-1;}
 disposeObject(o){o.traverse(n=>{n.geometry?.dispose();if(n.material){for(const m of Array.isArray(n.material)?n.material:[n.material]){m.map?.dispose();m.dispose();}}});}
 effect(e){if(e.type==='shot'){const material=new T.LineBasicMaterial({color:WEAPONS[e.weapon].color,transparent:true,opacity:.9});const obj=new T.Line(new T.BufferGeometry().setFromPoints([V(e.from.x,e.from.y,e.from.z),V(e.to.x,e.to.y,e.to.z)]),material);this.scene.add(obj);this.effects.push({obj,life:e.weapon===2?.3:.08,total:e.weapon===2?.3:.08});}
 if(e.type==='dash'){this.effect({type:'shot',weapon:4,actor:e.actor,from:e.from,to:e.to});}
 if(['explosion','death','power','spawn','jam'].includes(e.type)){const color=e.type==='explosion'?WEAPONS[e.weapon??1].color:e.type==='jam'?'#c99aff':e.type==='death'?CHARACTERS.find(c=>c.id===e.character).color:'#74f4de';const count=e.type==='death'?12:1;for(let i=0;i<count;i++){const mat=new T.MeshBasicMaterial({color,transparent:true,opacity:.65,wireframe:e.type==='power'||e.type==='spawn'});const obj=new T.Mesh(e.type==='death'?new T.BoxGeometry(.18,.18,.18):new T.IcosahedronGeometry(.3,1),mat);obj.position.set(e.pos.x,e.pos.y,e.pos.z);this.scene.add(obj);this.effects.push({obj,life:e.type==='death'?.6:.4,total:e.type==='death'?.6:.4,expand:e.type!=='death',velocity:e.type==='death'?V((Math.random()-.5)*6,Math.random()*5,(Math.random()-.5)*6):null});}}
  if((e.type==='shot'||e.type==='launch')&&e.actor===this.playerId)this.flashUntil=performance.now()+80;
 }
 render(mode,match,delta,time){if(mode==='selection'){const m=this.menu.model,reduced=window.matchMedia('(prefers-reduced-motion: reduce)').matches;m.rotation.y=Math.PI+.25+(reduced?0:Math.sin(time*.25)*.2);m.position.y=.17+(reduced?0:Math.sin(time)*.025);this.renderer.render(this.menu.scene,this.menu.camera);return;}
  if(!match)return;const player=match.actors.find(a=>a.id===this.playerId)||match.actors[0];this.camera.position.set(player.x,player.y+(player.health>0?1.45:.65),player.z);this.camera.rotation.set(player.pitch,player.yaw,0,'YXZ');
  match.actors.forEach((a,i)=>{const m=this.actorModels.get(a.id);if(!m)return;m.visible=a.id!==this.playerId&&a.health>0;m.position.set(a.x,a.y+.04,a.z);m.rotation.y=a.yaw;const moving=Math.min(1,Math.hypot(a.vx,a.vz)/5),swing=Math.sin(time*12+a.id)*.45*moving;m.userData.limbs.forEach((limb,j)=>{limb.rotation.x=j%2===1?(j===1?swing:-swing):-.2;});if(a.health>0&&a.active>0&&a.harness==='hermes'&&match.time-(m.userData.trailAt||0)>.1){m.userData.trailAt=match.time;const obj=new T.Mesh(new T.IcosahedronGeometry(.11,0),new T.MeshBasicMaterial({color:m.userData.color,transparent:true,opacity:.6}));obj.position.set(a.x,a.y+.4,a.z);this.scene.add(obj);this.effects.push({obj,life:.3,total:.3});}m.userData.torso.material.emissive.set(a.active>0&&['opencode','codex','cline','roo'].includes(a.harness)?m.userData.color:'#000000');m.userData.torso.material.emissiveIntensity=a.active>0?.7:0;m.userData.shield.material.color.set(a.slow>0?'#d89aff':m.userData.color);m.userData.shield.visible=a.slow>0||a.protection>0||(a.harness==='claudecode'&&a.active>0);if(m.userData.weapon.userData.type!==a.weapon){m.userData.gunAnchor.remove(m.userData.weapon);this.disposeObject(m.userData.weapon);m.userData.weapon=weaponModel(a.weapon);m.userData.weapon.scale.setScalar(.7);m.userData.gunAnchor.add(m.userData.weapon);}m.userData.weapon.userData.flash.visible=a.shotWait>WEAPONS[a.weapon].interval-.065;});
 match.pickups.forEach((p,i)=>{const m=this.pickupModels[i];m.visible=p.wait<=0;m.rotation.y=time*.8;m.position.y=p.y+Math.sin(time*2+i)*.07;});
 const ids=new Set();for(const r of match.rockets){ids.add(r.id);let m=this.rocketModels.get(r.id);if(!m){m=new T.Mesh(new T.SphereGeometry(r.weapon===4?.16:.12,8,6),new T.MeshBasicMaterial({color:WEAPONS[r.weapon??1].color}));this.scene.add(m);this.rocketModels.set(r.id,m);}m.position.set(r.pos.x,r.pos.y,r.pos.z);}for(const [id,m]of this.rocketModels)if(!ids.has(id)){this.scene.remove(m);this.disposeObject(m);this.rocketModels.delete(id);}
 for(const e of match.events)if(e.id>this.lastEvent){this.effect(e);this.lastEvent=e.id;}
 const alive=[];for(const e of this.effects){e.life-=delta;if(e.life<=0){this.scene.remove(e.obj);this.disposeObject(e.obj);}else{e.obj.material.opacity=e.life/e.total*.8;if(e.expand)e.obj.scale.addScalar(delta*14);if(e.velocity){e.obj.position.addScaledVector(e.velocity,delta);e.velocity.y-=15*delta;e.obj.rotation.x+=delta*5;}alive.push(e);}}this.effects=alive;
 this.hands.visible=player.health>0&&this.showWeapon!==false&&!this.spectator;if(this.currentWeapon!==player.weapon){for(const c of [...this.hands.children]){this.hands.remove(c);this.disposeObject(c);}this.firstPerson=weaponModel(player.weapon);this.firstPerson.scale.setScalar(1.1);this.hands.add(this.firstPerson);this.currentWeapon=player.weapon;this.firstPerson.traverse(m=>{if(m.isMesh){m.renderOrder=100;m.material.depthTest=false;}});}
 this.hands.position.set(.37,-.36,-.58+(this.flashUntil>performance.now()?.05:0));this.firstPerson.userData.flash.visible=this.flashUntil>performance.now();this.renderer.render(this.scene,this.camera);}
 dispose(){this.disposeObject(this.scene);this.disposeObject(this.menu.scene);this.renderer.dispose();}
}
export class SynthAudio{
 constructor(){this.ctx=null;this.muted=false;}
 start(){try{this.ctx??=new AudioContext();if(this.ctx.state==='suspended')this.ctx.resume();}catch{}}
 tone(freq,duration=.08,type='sine',gain=.04,end=0){if(!this.ctx||this.muted)return;const now=this.ctx.currentTime,o=this.ctx.createOscillator(),g=this.ctx.createGain();o.type=type;o.frequency.setValueAtTime(freq,now);if(end)o.frequency.exponentialRampToValueAtTime(end,now+duration);g.gain.setValueAtTime(gain,now);g.gain.exponentialRampToValueAtTime(.001,now+duration);o.connect(g);g.connect(this.ctx.destination);o.start(now);o.stop(now+duration);o.onended=()=>{o.disconnect();g.disconnect();};}
 event(e,player){if(e.type==='shot'||e.type==='launch'){const near=e.actor===0||Math.hypot((e.from?.x||e.pos?.x||0)-player.x,(e.from?.z||e.pos?.z||0)-player.z)<16;if(near)this.tone(e.weapon===2?900:e.weapon===1?100:240,.08,e.weapon===2?'sine':'sawtooth',e.actor===0?.035:.008,60);}
 if(e.type==='explosion')this.tone(80,.25,'sawtooth',.025,25);
 if(e.actor===0){if(e.type==='pickup')this.tone(700,.14,'sine',.035,1300);if(e.type==='damage')this.tone(120,.1,'triangle',.06,40);if(e.type==='power')this.tone(250,.3,'sine',.05,1000);if(e.type==='death')this.tone(200,.45,'sawtooth',.03,30);}}
 dispose(){this.ctx?.close();}
}
