import * as T from 'three';
import {SoftwareRenderer} from './software.mjs';
import {CHARACTERS,WEAPONS} from './data.mjs';
import {aim} from './core.mjs';
import {MAPS,pickupWeapon} from './maps.mjs';
import {normalizeDisplay} from './config.mjs';
import {WeaponFeedback,EffectPool} from './feedback.mjs';
import {terrainTriangles,terrainWallTriangles} from './terrain.mjs';
export {SynthAudio} from './feedback.mjs';
const V=(x=0,y=0,z=0)=>new T.Vector3(x,y,z);
const material=(color,metal=.5,rough=.42,emissive=false)=>new T.MeshStandardMaterial({color,metalness:metal,roughness:rough,...(emissive?{emissive:color,emissiveIntensity:1.6}:{})});
function box(parent,w,h,d,x,y,z,mat){const m=new T.Mesh(new T.BoxGeometry(w,h,d),mat);m.position.set(x,y,z);parent.add(m);return m;}
function cylinder(parent,r1,r2,h,x,y,z,mat,segments=12){const m=new T.Mesh(new T.CylinderGeometry(r1,r2,h,segments),mat);m.position.set(x,y,z);parent.add(m);return m;}
function ring(parent,r,t,x,y,z,mat,rx=Math.PI/2){const m=new T.Mesh(new T.TorusGeometry(r,t,6,32),mat);m.position.set(x,y,z);m.rotation.x=rx;parent.add(m);return m;}
const weaponInfo=type=>WEAPONS[type]||{color:['#ff6f91','#e8ff71','#ff9f43'][Math.abs(type)%3],name:`Weapon ${type}`,short:`W${type}`,feel:{}};
export function weaponModel(type=0){type=Number.isInteger(type)&&type>=0?type:0;const info=weaponInfo(type),g=new T.Group(),dark=material('#222f37'),light=material('#73848a'),glow=material(info.color,.3,.3,true);g.userData.type=type;
  if(type===0){box(g,.2,.23,.62,0,0,-.15,dark);box(g,.24,.1,.34,0,.16,-.18,light);box(g,.07,.045,.48,.105,.06,-.2,glow);const barrel=cylinder(g,.07,.07,.5,0,.01,-.6,light);barrel.rotation.x=Math.PI/2;box(g,.09,.17,.12,0,.25,-.03,dark);box(g,.09,.2,.14,0,-.19,.03,dark);}
 if(type===1){const barrel=cylinder(g,.22,.24,.9,0,0,-.25,dark);barrel.rotation.x=Math.PI/2;ring(g,.205,.037,0,0,-.72,glow,0);box(g,.3,.09,.55,0,.23,-.15,light);box(g,.15,.25,.19,0,-.26,.02,light);for(const x of [-.24,.24])box(g,.04,.24,.38,x,0,-.25,glow);}
 if(type===2){box(g,.21,.22,.7,0,0,-.26,dark);for(const x of [-.14,.14]){box(g,.075,.1,.92,x,.025,-.58,light);box(g,.035,.045,.8,x,.085,-.58,glow);}box(g,.15,.08,.25,0,.2,-.17,glow);box(g,.08,.2,.13,0,-.2,0,dark);}
 if(type===3){box(g,.36,.22,.5,0,0,-.1,dark);for(const x of [-.12,.12]){const barrel=cylinder(g,.095,.095,.58,x,.03,-.51,light);barrel.rotation.x=Math.PI/2;ring(g,.075,.017,x,.03,-.81,glow,0);}box(g,.32,.1,.25,0,-.13,-.32,glow);box(g,.12,.24,.13,0,-.22,.09,dark);}
  if(type===4){box(g,.23,.24,.62,0,0,-.2,dark);for(const z of [-.25,-.45,-.65])ring(g,.17,.025,0,0,z,glow,0);const core=new T.Mesh(new T.IcosahedronGeometry(.12,1),glow);core.position.z=-.67;g.add(core);for(const x of [-.18,.18])box(g,.08,.14,.7,x,0,-.3,light);box(g,.13,.22,.15,0,-.21,.05,dark);}
  if(type>=5){const feel=type%3;if(feel===0){box(g,.28,.22,.75,0,0,-.2,dark);box(g,.08,.08,1.05,0,.02,-.75,glow);box(g,.42,.08,.3,0,.2,.02,light);}else if(feel===1){const barrel=cylinder(g,.17,.22,.8,0,0,-.3,dark);barrel.rotation.x=Math.PI/2;for(const x of [-.19,.19])box(g,.06,.16,.7,x,0,-.45,glow);box(g,.26,.2,.2,0,-.2,.08,light);}else{box(g,.22,.3,.48,0,0,-.15,dark);const coil=cylinder(g,.18,.18,.7,0,0,-.62,glow,8);coil.rotation.x=Math.PI/2;box(g,.42,.06,.18,0,.12,-.34,light);}}
    const muzzle=info.feel?.muzzle||[.12,.06],flash=new T.Mesh(new T.SphereGeometry(muzzle[0],6,4),new T.MeshBasicMaterial({color:info.color}));flash.position.set(0,0,type===2?-1.05:-.83);flash.visible=false;g.add(flash);g.userData.flash=flash;g.userData.feel=info.feel;return g;}
export function vehicleModel(kind='puma'){const g=new T.Group(),dark=material('#26343a',.75,.4),body=material('#8f6f4d',.7,.38),trim=material('#d6b178',.4,.3),glow=material('#ffd166',.25,.25,true);box(g,2.1,.55,3.6,0,.48,0,body);box(g,1.7,.3,1.2,0,.86,.25,trim);for(const x of [-.95,.95])for(const z of [-1.05,1.05]){const wheel=cylinder(g,.35,.35,.22,x,.35,z,dark,12);wheel.rotation.z=Math.PI/2;}const guns=[];for(const x of [-.82,.82]){const mount=new T.Group();mount.position.set(x,1.08,.2);box(mount,.18,.18,.28,0,0,0,dark);const barrel=cylinder(mount,.09,.09,1.05,0,0,-.48,glow,10);barrel.rotation.x=Math.PI/2;const flash=new T.Mesh(new T.SphereGeometry(.16,6,4),new T.MeshBasicMaterial({color:'#fff0a5'}));flash.position.set(0,0,-1.03);flash.visible=false;mount.add(flash);g.add(mount);guns.push({mount,barrel,flash});}const roof=box(g,1.25,.12,1.4,0,1.04,.15,dark);g.userData={kind,vehicle:true,guns,roof,color:'#ffd166',flashUntil:0};return g;}
export function robotModel(id){const c=CHARACTERS.find(c=>c.id===id)||CHARACTERS[0],g=new T.Group(),armor=material(c.accent,.72,.32),color=material(c.color,.65,.3),dark=material('#17252b'),glow=material(c.color,.4,.2,true);
 const torso=box(g,.65,.6,.36,0,1.05,0,armor);box(g,.43,.26,.08,0,1.1,-.215,dark);box(g,.22,.055,.09,0,1.13,-.27,glow);box(g,.4,.16,.3,0,.66,0,dark);
 const head=new T.Group();head.position.set(0,1.56,0);g.add(head);
 if(id==='chatgpt'){const helmet=new T.Mesh(new T.IcosahedronGeometry(.28,1),armor);helmet.scale.set(1,.9,.88);head.add(helmet);ring(head,.16,.022,0,0,-.225,color,0);ring(head,.11,.017,0,0,-.238,glow,0);}
 else{box(head,.44,.36,.37,0,0,0,armor);box(head,.36,.07,.06,0,.01,-.2,glow);}
 if(id==='claude'){for(const x of [-.31,.31]){const fin=box(head,.09,.3,.24,x,.03,0,color);fin.rotation.z=x*-.5;}box(g,.12,.32,.1,0,1.08,-.26,color);}
 if(id==='grok'){box(head,.06,.34,.07,.22,.29,0,color);box(head,.14,.12,.12,-.17,.13,-.2,dark);box(g,.8,.15,.42,0,1.3,0,color);}
 if(id==='meta'){for(const x of [-.15,.15])ring(g,.17,.033,x,1.08,-.26,glow,0);}
 if(id==='qwen'){for(let i=0;i<3;i++)box(g,.67-i*.1,.07,.46,0,1.23-i*.13,0,color);const crown=box(head,.4,.12,.25,0,.24,0,color);crown.rotation.z=.15;}
 if(id==='gemini'){for(const x of [-.14,.14]){const star=new T.Mesh(new T.OctahedronGeometry(.13),glow);star.position.set(x,.04,-.24);head.add(star);}box(g,.04,.55,.08,0,1.05,-.25,color);}
 if(id==='deepseek'){const crest=box(head,.07,.35,.34,0,.23,.02,color);crest.rotation.z=-.15;for(const x of [-.33,.33])box(g,.09,.36,.48,x,1.1,0,color);}
 if(id==='mistral'){for(let i=0;i<3;i++){const fin=box(head,.14,.12,.15,.15-i*.15,.28+i*.05,0,color);fin.rotation.z=.2;}for(let i=0;i<3;i++)box(g,.48,.04,.05,0,.95+i*.12,-.25,glow);}
 if(id==='kimi'){ring(head,.32,.032,0,.03,0,glow,Math.PI/3);box(g,.13,.42,.06,-.18,1.03,-.23,color);box(g,.13,.42,.06,.18,1.03,-.23,color);}
 const limbs=[];for(const side of [-1,1]){const arm=new T.Group();arm.position.set(side*.45,1.28,0);g.add(arm);box(arm,.22,.2,.3,0,-.02,0,color);box(arm,.16,.4,.19,0,-.28,0,dark);box(arm,.19,.18,.21,0,-.48,-.035,armor);limbs.push(arm);
 const leg=new T.Group();leg.position.set(side*.2,.65,0);g.add(leg);box(leg,.24,.36,.27,0,-.15,0,armor);box(leg,.17,.27,.18,0,-.44,0,dark);box(leg,.26,.15,.39,0,-.61,-.07,color);box(leg,.08,.18,.03,0,-.37,-.13,glow);limbs.push(leg);}
 const gunAnchor=new T.Group();gunAnchor.position.set(.44,.84,-.12);g.add(gunAnchor);const weapon=weaponModel(0);weapon.scale.setScalar(.7);gunAnchor.add(weapon);
 const shield=new T.Mesh(new T.SphereGeometry(1.15,16,12),new T.MeshBasicMaterial({color:c.color,transparent:true,opacity:.13,wireframe:true}));shield.scale.set(.7,1,.7);shield.position.y=.9;g.add(shield);shield.visible=false;
 const base=new T.Mesh(new T.RingGeometry(.47,.54,28),new T.MeshBasicMaterial({color:c.color,side:T.DoubleSide,transparent:true,opacity:.7}));base.rotation.x=-Math.PI/2;base.position.y=.02;g.add(base);
 g.userData={limbs,head,torso,gunAnchor,weapon,shield,color:c.color};return g;}
function textLabel(parent,text,x,y,z,size=1,color='#8ad9d3',ry=0){const canvas=document.createElement('canvas');canvas.width=512;canvas.height=128;const ctx=canvas.getContext('2d');ctx.font='bold 78px monospace';ctx.textAlign='center';ctx.fillStyle=color;ctx.fillText(text,256,90);const tex=new T.CanvasTexture(canvas);const m=new T.Mesh(new T.PlaneGeometry(size*4,size),new T.MeshBasicMaterial({map:tex,transparent:true,depthWrite:false}));m.position.set(x,y,z);m.rotation.y=ry;m.userData.label=text;m.userData.labelSize=size*.6;parent.add(m);return m;}
function pointOf(value){if(Array.isArray(value))return {x:+value[0]||0,y:value.length>2?(+value[1]||0):0,z:+value[value.length>2?2:1]||0};return value?.position||value||{};}
function arenaBounds(arena){if(arena.bounds){const b=arena.bounds;return {minX:b.minX??b.left??-14,maxX:b.maxX??b.right??14,minZ:b.minZ??b.top??-14,maxZ:b.maxZ??b.bottom??14};}return {minX:-14,maxX:14,minZ:-14,maxZ:14};}
function traversalItems(arena,name){const t=arena.traversal||arena.traversalMetadata||{};return t[name]||arena[name]||[];}
export class ArenaView{
 constructor(canvas){const context=canvas.getContext('webgl2',{antialias:true,alpha:false});this.renderer=context?new T.WebGLRenderer({canvas,context,antialias:true,alpha:false,powerPreference:'high-performance'}):new SoftwareRenderer(canvas);this.display=normalizeDisplay();this.renderer.outputColorSpace=T.SRGBColorSpace;this.renderer.toneMapping=T.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1.2;
  this.scene=new T.Scene();this.scene.background=new T.Color('#090f17');this.scene.fog=new T.FogExp2('#090f17',.018);this.camera=new T.PerspectiveCamera(82,1,.08,220);this.camera.rotation.order='YXZ';this.scene.add(new T.HemisphereLight('#b2eeff','#1f252c',2));const sun=new T.DirectionalLight('#c9e5ef',2.8);sun.position.set(3,12,8);this.scene.add(sun);
      this.renderResources=new Set();this.buildArena();this.actorModels=new Map();this.vehicleModels=new Map();this.pickupModels=[];this.flagModels=new Map();this.lastEvent=0;this.flashUntil=0;this.playerId=0;this.spectator=false;this.hands=new T.Group();this.camera.add(this.hands);this.scene.add(this.camera);this.currentWeapon=-1;this.menu=this.makeMenu();this.resize();}
    setDisplay(prefs){const display=normalizeDisplay(prefs),scaleChanged=display.resolutionScale!==this.display?.resolutionScale;this.display=display;this.camera.fov=display.fov;this.camera.updateProjectionMatrix();this.showWeapon=display.showWeapon;if(scaleChanged)this.resize();}
   setPlayerId(id){if(this.playerId!==id){this.feedback?.reset();this.flashUntil=0;}this.playerId=id;}
   setSpectator(on){this.spectator=on===true;}
   resize(){const w=Math.max(1,this.renderer.domElement.clientWidth),h=Math.max(1,this.renderer.domElement.clientHeight),dpr=window.devicePixelRatio,baseline=this.renderer.isSoftware?.85:Math.min(Number.isFinite(dpr)&&dpr>0?dpr:1,1.5),ratio=baseline*(this.display?.resolutionScale??1);
    if(this.width===w&&this.height===h&&this.pixelRatio===ratio)return;
    if(this.pixelRatio!==ratio)this.renderer.setPixelRatio(ratio);
    // Keep even tiny/hidden canvases at least one backing pixel without changing CSS size.
    this.renderer.setSize(Math.max(w,1/ratio),Math.max(h,1/ratio),false);this.width=w;this.height=h;this.pixelRatio=ratio;
    this.camera.aspect=w/h;this.camera.updateProjectionMatrix();this.menu.camera.aspect=w/h;this.menu.camera.updateProjectionMatrix();}
    buildArena(arena=MAPS[0]){if(this.worldGroup){this.scene.remove(this.worldGroup);this.disposeObject(this.worldGroup);for(const resource of this.renderResources||[])resource.dispose();this.renderResources?.clear();}this.objectiveModels=new Map();this.mapId=arena.id;const world=new T.Group();this.worldGroup=world;this.scene.add(world);this.scene.background=new T.Color(arena.background);this.scene.fog=new T.FogExp2(arena.background,.018);const bounds=arenaBounds(arena),legacy=!arena.bounds,minX=bounds.minX,maxX=bounds.maxX,minZ=bounds.minZ,maxZ=bounds.maxZ,width=maxX-minX,depth=maxZ-minZ;
   const floor=material(arena.id==='foundry'?'#382c26':'#23313b',.65,.52),wall=material(arena.id==='crosswire'?'#25233e':'#19262f',.68,.5),trim=material('#45606a'),glow=material(arena.color,.4,.3,true),islands=arena.platforms?.length>0;
   if(!islands&&!arena.terrain){
   // Subdivide the floor: smaller surfaces also improve the software renderer's depth ordering.
   const tile=5;for(let x=minX+tile/2;x<maxX;x+=tile)for(let z=minZ+tile/2;z<maxZ;z+=tile)box(world,Math.min(tile,maxX-x+tile/2),.5,Math.min(tile,maxZ-z+tile/2),x,-.25,z,floor);
   const grid=new T.GridHelper(legacy?28:Math.max(width,depth),legacy?14:Math.max(1,Math.round(Math.max(width,depth)/2)),arena.color,'#304752');grid.position.set((minX+maxX)/2,.006,(minZ+maxZ)/2);world.add(grid);
   }else if(islands){
   const voidMat=material(arena.background,.1,.9),platformMat=material('#263f4c',.6,.46),routeMats={north:material('#d5a45c',.35,.35,true),middle:material('#69d6e8',.35,.35,true),south:material('#b28cff',.35,.35,true)},supportMat=material('#14242e',.72,.56);
   box(world,width+70,.25,depth+70,(minX+maxX)/2,(arena.voidY??-8)-3,(minZ+maxZ)/2,voidMat);
   for(const p of arena.platforms){const y=p.y??p.topY??0,thickness=p.thickness??.7,mat=routeMats[p.route]||platformMat;box(world,p.w,thickness,p.d,p.x,y-thickness/2,p.z,platformMat);box(world,Math.max(.2,p.w-.28),.045,Math.max(.2,p.d-.28),p.x,y+.025,p.z,mat);for(const [sx,sz] of [[-1,-1],[-1,1],[1,-1],[1,1]])cylinder(world,.12,.16,3,p.x+sx*(p.w/2-1),y-1.5,p.z+sz*(p.d/2-1),supportMat,8);}
   for(const landmark of arena.landmarks||[])textLabel(world,landmark.label,landmark.x,landmark.y??3,landmark.z,.55,arena.color);
   }
   if(arena.terrain){
    const terrainMaterials={grass:material('#66844d',.25,.8),dirt:material('#9a7046',.3,.88),rock:material('#69757a',.62,.76),cliff:material('#4b5558',.72,.84)};
    const addTerrainMesh=(triangles,side=false)=>{const groups=new Map();for(const triangle of triangles){const key=triangle.material||'rock';const positions=groups.get(key)||[];for(const point of triangle.vertices)positions.push(point[0],point[1],point[2]);groups.set(key,positions);}for(const [key,positions] of groups){const geometry=new T.BufferGeometry();geometry.setAttribute('position',new T.Float32BufferAttribute(positions,3));geometry.computeVertexNormals();const mat=terrainMaterials[key]||terrainMaterials.rock;if(side)mat.side=T.DoubleSide;const mesh=new T.Mesh(geometry,mat);mesh.userData.terrain=true;world.add(mesh);}}
    addTerrainMesh(terrainTriangles(arena.terrain));addTerrainMesh(terrainWallTriangles(arena.terrain),true);
   }
 for(const b of arena.blocks){box(world,b.w,b.h,b.d,b.x,b.h/2,b.z,b.kind==='reactor'?material('#2f4249'):wall);
 if(b.kind==='cover'){box(world,b.w+.03,.055,b.d+.03,b.x,b.h-.15,b.z,glow);box(world,b.w-.3,.4,.04,b.x,b.h*.5,b.z+b.d/2+.01,trim);}
 if(b.kind==='reactor'){for(const y of [.3,2.8,b.h+.06]){const rim=box(world,b.w+.08,.055,b.d+.08,b.x,y,b.z,glow);}for(const x of [-b.w*.32,b.w*.32])box(world,.055,b.h-.5,.045,b.x+x,b.h/2,b.z+b.d/2+.02,glow);}
 if(b.kind==='wall')for(let j=-12;j<=12;j+=4){const x=b.w>5?j:b.x,z=b.d>5?j:b.z;box(world,b.w>5?.25:1.1,8,b.d>5?.25:1.1,x,4,z,trim);}}
 if(arena.raised){for(const x of [-11.05,11.05]){const length=Math.hypot(12,3.8),ramp=box(world,5.5,.18,length,x,1.83,-3,floor);ramp.rotation.x=Math.atan(3.8/12);for(const sx of [-2.2,2.2]){const strip=box(world,.06,.04,length,x+sx,1.96,-3,glow);strip.rotation.x=Math.atan(3.8/12);}}box(world,27,.06,.07,0,3.84,-9,glow);}
 if(arena.id==='crosswire'){for(const x of [-1.6,1.6])box(world,.055,.03,26,x,.04,0,glow);for(const z of [-1.6,1.6])box(world,26,.03,.055,0,.04,z,glow);ring(world,2,.025,0,6.2,0,glow);}
 if(arena.id==='exchange')for(const y of [.25,3.5,5.5])ring(world,2.1,.055,0,y,0,glow);
 if(arena.id==='foundry')for(const x of [-4,4]){for(const z of [-2,0,2])box(world,1.8,.03,.35,x,5.77,z,glow);textLabel(world,'HOT',x,4,2.52,.35,'#ffc684');}
    if(!islands&&!arena.terrain){const edge=legacy?13.94:maxX-.06;textLabel(world,arena.name.toUpperCase(),(minX+maxX)/2,6.5,minZ+.06,1.3);textLabel(world,'02',minX+.06,5.8,(minZ+maxZ)/2,1.2,arena.color,Math.PI/2);textLabel(world,'01',maxX-.06,5.8,(minZ+maxZ)/2,1.2,arena.color,-Math.PI/2);for(const x of legacy?[-7,7]:[(minX+maxX)/2-width*.25,(minX+maxX)/2+width])box(world,.07,.04,depth*.77,x,.06,(minZ+maxZ)/2,glow);for(const z of legacy?[-10,0,10]:[minZ+depth/6,(minZ+maxZ)/2,maxZ-depth/6]){box(world,width,.3,.35,(minX+maxX)/2,8.5,z,trim);box(world,width*.72,.05,.15,(minX+maxX)/2,8.32,z,glow);}for(const x of legacy?[-12,12]:[minX+2,maxX-2]){const light=new T.PointLight(arena.color,28,15,2);light.position.set(x,5,(minZ+maxZ)/2);world.add(light);}}
  this.addTraversal(world,arena,glow);
  }
    addTraversal(world,arena,glow){const pads=[...traversalItems(arena,'trampolines'),...traversalItems(arena,'pads')],launchers=[...traversalItems(arena,'boostLaunchers'),...traversalItems(arena,'launchers')];const shared=this.renderResources??=new Set(),padGeo=new T.CylinderGeometry(.7,.7,.12,16),padMat=material(arena.color,.25,.25,true),launchGeo=new T.BoxGeometry(.8,.1,1.3),launchMat=material(arena.color,.25,.25,true);shared.add(padGeo).add(padMat).add(launchGeo).add(launchMat);for(const raw of pads){const p=pointOf(raw),y=p.y??0,m=new T.Mesh(padGeo,padMat);m.position.set(p.x,y+.06,p.z);m.userData.traversal='trampoline';world.add(m);ring(world,.78,.035,p.x,y+.13,p.z,padMat); }for(const raw of launchers){const p=pointOf(raw),y=p.y??0,m=new T.Mesh(launchGeo,launchMat);m.position.set(p.x,y+.05,p.z);m.rotation.y=raw.rotation??raw.yaw??(Array.isArray(raw.dir)?Math.atan2(raw.dir[0],raw.dir[1]):0);m.userData.traversal='boost-launcher';world.add(m);for(const s of [-.25,.25])box(world,.06,.04,.9,p.x+s,y+.13,p.z,glow);}for(const link of arena.jumpLinks||[]){const from=pointOf(link.source),to=pointOf(link.target),mid=V((from.x+to.x)/2,Math.max(from.y??0,to.y??0)+4,(from.z+to.z)/2),geo=new T.BufferGeometry().setFromPoints([V(from.x,(from.y??0)+.14,from.z),mid,V(to.x,(to.y??0)+.14,to.z)]),arc=new T.Line(geo,glow);arc.userData.traversal='jump-link';world.add(arc);}}
 makeMenu(){const scene=new T.Scene();scene.background=new T.Color('#080f13');scene.fog=new T.FogExp2('#080f13',.055);const camera=new T.PerspectiveCamera(38,1,.1,80);camera.position.set(5,3.3,10);camera.lookAt(0,1.4,0);scene.add(new T.HemisphereLight('#bdedee','#233139',2.8));const key=new T.DirectionalLight('#e4fff3',4);key.position.set(-4,6,5);scene.add(key);const rim=new T.PointLight('#52e5cf',80,15);rim.position.set(3,3,-3);scene.add(rim);
 const dark=material('#152128',.8,.4),glow=material('#67e7d3',.4,.2,true);box(scene,50,.3,50,0,-.35,0,dark);const grid=new T.GridHelper(40,40,'#284443','#192c31');grid.position.y=-.19;scene.add(grid);cylinder(scene,1.55,1.8,.3,0,-.02,0,dark,48);ring(scene,1.57,.018,0,.15,0,glow);ring(scene,2.05,.014,0,-.16,0,glow);ring(scene,2.2,.01,0,-.16,0,glow);
 for(let i=-4;i<=4;i++){box(scene,.25,9,.5,i*3,4,-6,dark);box(scene,.045,6,.04,i*3+.18,4,-5.72,glow);}
 const model=robotModel('chatgpt');model.scale.setScalar(2.15);model.position.y=.17;model.rotation.y=.25;scene.add(model);return {scene,camera,model,id:'chatgpt'};}
 setCharacter(id){if(id===this.menu.id)return;this.disposeObject(this.menu.model);this.menu.scene.remove(this.menu.model);this.menu.model=robotModel(id);this.menu.model.scale.setScalar(2.15);this.menu.model.position.y=.17;this.menu.scene.add(this.menu.model);this.menu.id=id;}
      setMatch(match){const arena=match.arena||MAPS.find(a=>a.id===match.mapId)||MAPS[0];if(this.mapId!==arena.id)this.buildArena(arena);this.clearObjectiveMarkers();for(const m of [...this.actorModels.values(),...this.pickupModels,...(this.flagModels||new Map()).values()]){this.scene.remove(m);this.disposeObject(m);}this.flagModels=new Map();this.actorModels=new Map((match.actors||[]).map(a=>{const m=robotModel(a.character);this.scene.add(m);return [a.id,m];}));this.pickupModels=(match.pickups||[]).map(p=>{const g=new T.Group(),colors={health:'#77efba',armor:'#6dbfff',rocket:'#ffb164',rail:'#bf9cff',scatter:'#ffde87',plasma:'#72cfff',grenade:'#ff806b',shock:'#8ce8ff',flak:'#ffd166',haste:'#72f1b8',overcharge:'#ff8f70',overshield:'#75baff'},mat=material(colors[p.kind]||'#8ad9d3',.4,.3,true);if(p.kind==='health'){box(g,.6,.19,.19,0,.65,0,mat);box(g,.19,.6,.19,0,.65,0,mat);}else if(p.kind==='armor'){const m=new T.Mesh(new T.OctahedronGeometry(.4),mat);m.position.y=.7;g.add(m);}else if(['haste','overcharge','overshield'].includes(p.kind)){const m=new T.Mesh(new T.IcosahedronGeometry(.36,1),mat);m.position.y=.7;g.add(m);ring(g,.55,.022,0,.07,0,mat);}else{const w=weaponModel(pickupWeapon(p.kind));w.position.y=.75;w.scale.setScalar(.7);g.add(w);}if(!['haste','overcharge','overshield'].includes(p.kind))ring(g,.55,.022,0,.07,0,mat);g.position.set(p.x||0,p.y||0,p.z||0);this.scene.add(g);return g;});this.syncVehicles(match);this.updateFlags(match,arena);this.updateObjectives(match,arena);this.effectPool?.clear();this.projectilePool?.clear();this.feedback?.reset();this.flashUntil=0;this.lastEvent=match.serial||0;this.currentWeapon=-1;}
   createFlagModel(team,arena){const resources=this.renderResources??=new Set(),color=team===0||team==='0'?arena.color:'#ff789d';const poleGeo=resources.flagPoleGeo??=new T.CylinderGeometry(.035,.05,1.8,8),bannerGeo=resources.flagBannerGeo??=new T.BoxGeometry(.52,.32,.035),baseGeo=resources.flagBaseGeo??=new T.CylinderGeometry(.34,.42,.08,16),mat=resources[`flagMat${team}`]??=material(color,.35,.3,true);resources.add(poleGeo);resources.add(bannerGeo);resources.add(baseGeo);resources.add(mat);const g=new T.Group();const pole=new T.Mesh(poleGeo,mat);pole.position.y=.9;g.add(pole);const banner=new T.Mesh(bannerGeo,mat);banner.position.set(.24,1.55,0);g.add(banner);const base=new T.Mesh(baseGeo,mat);base.position.y=.04;g.add(base);g.userData={team,flag:true,banner};return g;}
     updateFlags(match,arena=MAPS[0]){this.updateVehicleModels(match);const input=match?.flags;if(!input){for(const g of this.flagModels?.values()||[])g.visible=false;return;}const flags=Array.isArray(input)?input:Object.entries(input).map(([team,flag])=>({...flag,team:flag?.team??team}));const active=new Set();for(const flag of flags.slice(0,8)){if(!flag)continue;const team=flag.team??flag.teamId??flag.id??0,key=String(team);let g=this.flagModels.get(key);if(!g){g=this.createFlagModel(team,arena);this.flagModels.set(key,g);this.scene.add(g);}active.add(key);const carrier=flag.carrier??flag.carrierId??flag.carriedBy;g.visible=carrier==null&&flag.state!=='carried'&&flag.status!=='carried';const p=pointOf(flag);g.position.set(p.x||0,p.y||0,p.z||0);g.rotation.y=flag.yaw??0;const dropped=flag.dropped===true||flag.state==='dropped'||flag.status==='dropped';const pulse=dropped&&!this.motionQuery?.matches;g.scale.setScalar(pulse?1+Math.sin((match.time||0)*7)*.08:1);g.userData.banner.material.opacity=dropped?.75:1;g.userData.banner.material.transparent=true;}for(const [key,g] of this.flagModels)if(!active.has(key))g.visible=false;}
     objectiveColor(team,arena,neutral='#55ddcc'){if(team===null||team===undefined)return neutral;return String(team)==='0'?arena.color:'#ff789d';}
     createObjectiveModel(zone,arena){const radius=Math.max(.8,Number(zone.radius)||3.5),g=new T.Group(),baseMat=material(this.objectiveColor(zone.owner,arena),.25,.3,true),progressMat=material('#ffd166',.2,.25,true),beacon=cylinder(g,.09,.16,1.35,0,.68,0,baseMat,10),base=ring(g,radius,.075,0,.035,0,baseMat),progress=new T.Mesh(new T.RingGeometry(radius-.16,radius+.16,32,1,0,0),progressMat);progress.rotation.x=-Math.PI/2;progress.position.y=.045;g.add(progress);g.userData={objective:true,base,beacon,progress,baseMat,progressMat,radius};return g;}
     clearObjectiveMarkers(){for(const g of this.objectiveModels?.values()||[]){this.worldGroup?.remove(g);this.disposeObject(g);}this.objectiveModels?.clear();}
      updateObjectives(match,arena=MAPS[0]){const input=match?.objectives;if(!input||!['koth','domination'].includes(input.kind)){this.clearObjectiveMarkers();return;}this.objectiveModels??=new Map();const active=new Set(),reduced=this.motionQuery?.matches===true;for(const zone of input.zones||[]){if(!zone)continue;const key=String(zone.id??active.size),p=pointOf(zone),owner=zone.contested?'contested':zone.owner,capture=zone.captureTeam??zone.owner,progress=Math.max(0,Math.min(100,Number(zone.progress)||0));let g=this.objectiveModels.get(key);if(!g){g=this.createObjectiveModel(zone,arena);this.objectiveModels.set(key,g);this.worldGroup?.add(g);}active.add(key);const color=zone.contested?'#ffd166':this.objectiveColor(owner,arena),progressColor=zone.contested?'#ffd166':this.objectiveColor(capture,arena);g.position.set(p.x||0,p.y||0,p.z||0);g.userData.baseMat.color.set(color);g.userData.baseMat.emissive.set(color);g.userData.beacon.material=g.userData.baseMat;g.userData.progressMat.color.set(progressColor);g.userData.progressMat.emissive.set(progressColor);g.userData.progressMat.opacity=progress>0?1:0;g.userData.progressMat.transparent=true;if(g.userData.progressValue!==progress){g.userData.progress.geometry.dispose();g.userData.progress.geometry=new T.RingGeometry(g.userData.radius-.16,g.userData.radius+.16,32,1,0,Math.PI*2*progress/100);g.userData.progressValue=progress;}g.userData.progress.visible=progress>0;g.scale.y=reduced?1:1+.06*Math.sin((match.time||0)*4+(zone.id?.length||0));}for(const [key,g] of this.objectiveModels)if(!active.has(key)){this.worldGroup?.remove(g);this.disposeObject(g);this.objectiveModels.delete(key);}}
    updateVehicleModels(match){for(const vehicle of match.vehicles||[]){const model=this.vehicleModels?.get(vehicle.id);if(!model)continue;const p=vehicle.position||vehicle;model.visible=(vehicle.health??1)>0&&(vehicle.respawnTimer??0)<=0;model.position.set(p.x||0,p.y||0,p.z||0);model.rotation.y=vehicle.heading??vehicle.yaw??0;const heat=vehicle.heat??0;for(const gun of model.userData.guns||[]){gun.mount.scale.setScalar(1+heat*.08);gun.flash.visible=!this.motionQuery?.matches&&model.userData.flashUntil>performance.now();}}}
    syncVehicles(match){this.vehicleModels??=new Map();const active=new Set((match.vehicles||[]).map(vehicle=>vehicle.id));for(const [id,model] of this.vehicleModels)if(!active.has(id)){this.scene.remove(model);this.disposeObject(model);this.vehicleModels.delete(id);}for(const vehicle of match.vehicles||[]){if(this.vehicleModels.has(vehicle.id))continue;const model=vehicleModel(vehicle.kind);this.vehicleModels.set(vehicle.id,model);this.scene.add(model);}}
    disposeObject(o){if(!o?.traverse)return;const shared=this.renderResources||new Set(),geometries=new Set(),materials=new Set(),textures=new Set();o.traverse(n=>{if(n.geometry&&!shared.has(n.geometry))geometries.add(n.geometry);if(n.material)for(const m of Array.isArray(n.material)?n.material:[n.material])if(!shared.has(m)){materials.add(m);if(m.map)textures.add(m.map);}});for(const r of [...geometries,...materials,...textures])r.dispose();}
   effect(e){if(!e)return;this.effectPool??=new EffectPool(this.scene);this.feedback??=new WeaponFeedback();const reduced=this.motionQuery?.matches===true,info=weaponInfo(e.weapon??0);
     if(e.type==='shot'||e.type==='vehicle-shot'||e.type==='launch'||e.type==='dash'){const from=e.from,to=e.to??e.pos,feel=info.feel||{},tracer=feel.tracer||[.085,.055],color=e.type==='vehicle-shot'?'#ffd166':info.color;if(from&&to)this.effectPool.add({from,to,color,life:e.type==='dash'?.12:tracer[0],size:tracer[1]});if(e.type==='launch'&&to)this.effectPool.add({pos:to,color,size:(feel.muzzle?.[0]||.12)*1.4,life:feel.muzzle?.[1]||.06});if((e.type==='shot'||e.type==='vehicle-shot')&&to){const impact=feel.impactVisual==='wide'?.14:feel.impactVisual==='ring'?.12:feel.impactVisual==='burst'?.16:.09;this.effectPool.add({pos:to,color:e.hit?'#fff2ce':color,size:e.hit?impact:.055,life:e.hit?.18:.1,expand:reduced?0:(feel.impactVisual==='ring'?1.2:.25)});}}
     if(['explosion','death','power','powerup','spawn','jam','flag-pickup','flag-drop','flag-return','capture'].includes(e.type)){const color=e.type==='explosion'?info.color:e.type==='jam'?'#c99aff':e.type==='powerup'?'#ffcf70':e.type.startsWith('flag')||e.type==='capture'?(e.team===0?'#68c8ff':'#ff789d'):e.type==='death'?(CHARACTERS.find(c=>c.id===e.character)?.color??'#fff2ce'):'#74f4de';const impact=info.feel?.impactVisual,count=e.type==='death'&&!reduced?8:1,size=e.type==='death'?.12:impact==='wide'?.42:impact==='burst'?.34:impact==='ring'?.22:.3;if(e.pos)for(let i=0;i<count;i++)this.effectPool.add({pos:e.pos,color,size,life:e.type==='death'?.5:impact==='ring'?.4:.3,expand:reduced||e.type==='death'?0:impact==='ring'?1.5:3,wireframe:e.type==='power'||e.type==='powerup'||e.type==='spawn',velocity:e.type==='death'&&!reduced?V((Math.random()-.5)*4,Math.random()*3,(Math.random()-.5)*4):null});}
     if(e.type==='shot'||e.type==='launch'){const model=this.actorModels?.get(e.actor);if(model)model.userData.flashUntil=performance.now()+45;if(e.actor===this.playerId){this.feedback.shot(e.weapon,e.time);this.flashUntil=performance.now()+45;}}if(e.type==='vehicle-shot'){const model=this.vehicleModels?.get(e.vehicle);if(model)model.userData.flashUntil=performance.now()+45;if(e.actor===this.playerId&&e.barrel===0){this.feedback.shot(0,e.time);this.flashUntil=performance.now()+45;}}
 }
   render(mode,match,delta,time){this.resize();this.motionQuery??=window.matchMedia?.('(prefers-reduced-motion: reduce)');const reduced=this.motionQuery?.matches===true;if(mode==='selection'){const m=this.menu.model;m.rotation.y=Math.PI+.25+(reduced?0:Math.sin(time*.25)*.2);m.position.y=.17+(reduced?0:Math.sin(time)*.025);this.renderer.render(this.menu.scene,this.menu.camera);return;}
      if(!match)return;const actors=match.actors||[],player=actors.find(a=>a.id===this.playerId)||actors[0];if(!player)return;const arena=match.arena||MAPS.find(a=>a.id===match.mapId)||MAPS[0];this.updateFlags(match,arena);this.updateObjectives(match,arena);this.camera.position.set(player.x||0,(player.y||0)+(player.health>0?1.45:.65),player.z||0);this.camera.rotation.set(player.pitch||0,player.yaw||0,0,'YXZ');
      actors.forEach((a,i)=>{const m=this.actorModels.get(a.id);if(!m)return;m.visible=a.id!==this.playerId&&a.health>0&&a.vehicleId==null;m.position.set(a.x||0,(a.y||0)+.04,a.z||0);m.rotation.y=a.yaw||0;const moving=Math.min(1,Math.hypot(a.vx||0,a.vz||0)/5),swing=Math.sin(time*12+a.id)*.45*moving;m.userData.limbs.forEach((limb,j)=>{limb.rotation.x=j%2===1?(j===1?swing:-swing):-.2;});if(!reduced&&a.health>0&&a.active>0&&a.harness==='hermes'&&(match.time||0)-(m.userData.trailAt||0)>.1){m.userData.trailAt=match.time;this.effectPool??=new EffectPool(this.scene);this.effectPool.add({pos:V(a.x,a.y+.4,a.z),color:m.userData.color,size:.11,life:.3});}m.userData.torso.material.emissive.set(a.active>0&&['opencode','codex','cline','roo'].includes(a.harness)?m.userData.color:'#000000');m.userData.torso.material.emissiveIntensity=a.active>0?.7:0;m.userData.shield.material.color.set(a.slow>0?'#d89aff':m.userData.color);m.userData.shield.visible=a.slow>0||a.protection>0||(a.harness==='claudecode'&&a.active>0);if(m.userData.weapon.userData.type!==a.weapon){m.userData.gunAnchor.remove(m.userData.weapon);this.disposeObject(m.userData.weapon);m.userData.weapon=weaponModel(a.weapon);m.userData.weapon.scale.setScalar(.7);m.userData.gunAnchor.add(m.userData.weapon);}m.userData.weapon.userData.flash.visible=!reduced&&(m.userData.flashUntil??0)>performance.now();});
   (match.pickups||[]).forEach((p,i)=>{const m=this.pickupModels[i];if(!m)return;m.visible=(p.wait||0)<=0;m.rotation.y=reduced?0:time*.8;m.position.y=(p.y||0)+(reduced?0:Math.sin(time*2+i)*.07);});
   this.projectilePool??=new EffectPool(this.scene,64);this.projectilePool.clear();for(const r of (match.rockets||[]).slice(0,64))if(r.pos)this.projectilePool.add({pos:r.pos,color:weaponInfo(r.weapon??0).color,size:r.weapon===4?.16:.12,life:1});
 for(const e of match.events)if(e.id>this.lastEvent){this.effect(e);this.lastEvent=e.id;}
  this.effectPool?.update(Math.max(0,delta));
   this.hands.visible=player.health>0&&this.showWeapon!==false&&!this.spectator&&player.vehicleId==null;if(this.currentWeapon!==player.weapon){for(const c of [...this.hands.children]){this.hands.remove(c);this.disposeObject(c);}this.firstPerson=weaponModel(player.weapon);this.firstPerson.scale.setScalar(1.1);this.hands.add(this.firstPerson);this.currentWeapon=player.weapon;this.firstPerson.traverse(m=>{if(m.isMesh){m.renderOrder=100;m.material.depthTest=false;}});}
  this.feedback??=new WeaponFeedback();const pose=this.feedback.update(player,delta,reduced,this.hands.visible);this.hands.position.set(.37+pose.x,-.36+pose.y,-.58+pose.z);this.hands.rotation.set(pose.pitch,0,pose.roll);this.firstPerson.userData.flash.visible=!reduced&&this.hands.visible&&this.flashUntil>performance.now();this.renderer.render(this.scene,this.camera);}
    dispose(){this.clearObjectiveMarkers();this.effectPool?.dispose();this.projectilePool?.dispose();this.disposeObject(this.scene);this.disposeObject(this.menu.scene);for(const resource of this.renderResources||[])resource.dispose();this.renderResources?.clear();this.renderer.dispose();}
}
