'use client';
import {Slider} from '@/components/ui/slider';
import {Switch} from '@/components/ui/switch';
import {RadioGroup,RadioGroupItem} from '@/components/ui/radio-group';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {DEFAULT_CONFIG,DEFAULT_DISPLAY,GAME_MODES,DIFFICULTIES} from '../../game/config.mjs';
import {WEAPONS} from '../../game/data.mjs';

function Choice({label,value,options,onChange,disabled=false}:any){return <div className="config-field"><span>{label}</span><Select value={String(value)} onValueChange={onChange} disabled={disabled}><SelectTrigger aria-label={label}><SelectValue/></SelectTrigger><SelectContent className="arena-select">{options.map((o:any)=><SelectItem key={o[0]} value={String(o[0])}>{o[1]}</SelectItem>)}</SelectContent></Select></div>;}
function Range({label,value,min,max,step=1,onChange,suffix=''}:any){return <div className="config-field"><label>{label}<output>{value}{suffix}</output></label><Slider aria-label={label} value={[value]} min={min} max={max} step={step} onValueChange={([v])=>onChange(v)}/></div>;}
function Toggle({label,checked,onChange,disabled=false}:any){return <label className="config-toggle"><span>{label}</span><Switch aria-label={label} checked={checked} onCheckedChange={onChange} disabled={disabled}/></label>;}
export function MatchConfiguration({config,onChange}:any){const patch=(key:string,value:any)=>onChange({...config,[key]:value});const mode=GAME_MODES.find(m=>m.id===config.mode)!;return <section id="match-setup" className="match-configuration">
 <div className="section-label"><span>04 / MATCH SETUP</span><button className="text-button" onClick={()=>onChange({...DEFAULT_CONFIG})}>RESET MATCH RULES</button></div>
 <RadioGroup className="mode-options" aria-label="Game mode" value={config.mode} onValueChange={v=>patch('mode',v)}>{GAME_MODES.map(m=><label className={`mode-option ${config.mode===m.id?'selected':''}`} key={m.id} htmlFor={`mode-${m.id}`}><div><strong>{m.name}</strong><small>{m.description}</small></div><RadioGroupItem id={`mode-${m.id}`} value={m.id} aria-label={m.name}/></label>)}</RadioGroup>
 <div className="config-grid">
 <div className="config-block"><h3>Opponents</h3><Range label="Bot count" value={config.botCount} min={0} max={8} onChange={(v:number)=>patch('botCount',v)}/><Choice label="Bot difficulty" value={config.difficulty} options={DIFFICULTIES.map(d=>[d.id,d.name])} onChange={(v:string)=>patch('difficulty',v)} disabled={config.botCount===0}/><p>{config.botCount===0?'Solo practice: explore and test weapons until the timer ends.':DIFFICULTIES.find(d=>d.id===config.difficulty)?.description} Bots share your health, damage and movement rules.</p><label className="config-field">Your callsign<input aria-label="Your callsign" maxLength={20} placeholder="Use operator name" value={config.playerName} onChange={e=>patch('playerName',e.target.value)}/></label></div>
 <div className="config-block"><h3>Match rules</h3><Range label="Frag limit" value={config.fragLimit} min={5} max={50} step={5} onChange={(v:number)=>patch('fragLimit',v)}/><Range label="Time limit" value={config.timeLimit/60} min={1} max={15} suffix=" min" onChange={(v:number)=>patch('timeLimit',v*60)}/><Range label="Respawn delay" value={config.respawn} min={1} max={5} suffix=" sec" onChange={(v:number)=>patch('respawn',v)}/><Choice label="Starting weapon" value={config.startingWeapon} options={WEAPONS.map((w,i)=>[i,w.name])} onChange={(v:string)=>patch('startingWeapon',Number(v))} disabled={config.mode!=='deathmatch'}/><p>{config.mode!=='deathmatch'?`${mode.name} controls spawn weapons and ammunition.`:'Your chosen weapon is restored on every spawn.'}</p></div>
 <div className="config-block"><h3>Modifiers</h3><Choice label="Movement speed" value={config.speed} options={[[.75,'0.75× • tactical'],[1,'1× • classic'],[1.25,'1.25× • fast'],[1.5,'1.5× • turbo']]} onChange={(v:string)=>patch('speed',Number(v))}/><Choice label="Gravity" value={config.gravity} options={[[1,'Normal'],[.7,'Light • 70%'],[.4,'Moon • 40%']]} onChange={(v:string)=>patch('gravity',Number(v))}/><Choice label="Damage multiplier" value={config.damage} options={[[.5,'0.5×'],[1,'1×'],[1.5,'1.5×'],[2,'2×']]} onChange={(v:string)=>patch('damage',Number(v))} disabled={config.mode==='instagib'}/><Toggle label="Unlimited unlocked ammo" checked={config.mode!=='deathmatch'||config.unlimitedAmmo} onChange={(v:boolean)=>patch('unlimitedAmmo',v)} disabled={config.mode!=='deathmatch'}/><Toggle label="Half ability cooldowns" checked={config.fastPowers&&config.mode!=='instagib'} onChange={(v:boolean)=>patch('fastPowers',v)} disabled={config.mode==='instagib'}/><Toggle label="Life steal • heal 25% of damage" checked={config.lifeSteal} onChange={(v:boolean)=>patch('lifeSteal',v)}/></div>
 </div><p className="config-note">Saved on this device. Match rules apply when you enter the arena or start a new match.</p>
 </section>;}
export function DisplayConfiguration({display,onChange}:any){const patch=(key:string,value:any)=>onChange({...display,[key]:value});return <div className="display-configuration"><h3>View & crosshair</h3><Range label="Field of view" value={display.fov} min={65} max={110} suffix="°" onChange={(v:number)=>patch('fov',v)}/><Choice label="Crosshair shape" value={display.crosshair} options={['cross','dot','ring'].map(v=>[v,v[0].toUpperCase()+v.slice(1)])} onChange={(v:string)=>patch('crosshair',v)}/><Range label="Crosshair size" value={display.size} min={.6} max={1.8} step={.1} suffix="×" onChange={(v:number)=>patch('size',v)}/><div className="crosshair-editor"><label>Crosshair color<input type="color" aria-label="Crosshair color" value={display.color} onChange={e=>patch('color',e.target.value)}/></label><div className="crosshair-preview"><div className={`crosshair shape-${display.crosshair}`} style={{'--crosshair-color':display.color,'--crosshair-size':display.size} as any}><span/><span/><span/><span/></div></div></div><Toggle label="Show weapon model" checked={display.showWeapon} onChange={(v:boolean)=>patch('showWeapon',v)}/><Toggle label="Show FPS counter" checked={display.showFps} onChange={(v:boolean)=>patch('showFps',v)}/><button className="text-button" onClick={()=>onChange({...DEFAULT_DISPLAY})}>RESET VIEW</button></div>;}
