'use client';
import {useEffect,useRef,useState} from 'react';
import {ArrowUpRight,AudioLines,Check,ChevronRight,Crosshair,Hexagon,LockKeyhole,Pause,Play,RotateCcw,Shield,SkipForward,Sparkles,Terminal,Volume2,VolumeX,Zap} from 'lucide-react';
import {Slider} from '@/components/ui/slider';
import {RadioGroup,RadioGroupItem} from '@/components/ui/radio-group';
import {MAPS,getMap} from '../game/maps.mjs';
import {Switch} from '@/components/ui/switch';
import {CHARACTERS,HARNESSES,WEAPONS,RULES,resolveLoadout} from '../game/data.mjs';
import {Match} from '../game/core.mjs';
import {NetClient,DEFAULT_SERVER_URL} from '../game/net.mjs';
import {DEFAULT_CONFIG,DEFAULT_DISPLAY,normalizeConfig,normalizeDisplay,GAME_MODES} from '../game/config.mjs';
import {MatchConfiguration,DisplayConfiguration} from './game-ui/configuration';

type Mode='selection'|'browse'|'lobby'|'playing'|'paused'|'results';
const defaultNetUrl=typeof window!=='undefined'&&!['localhost','127.0.0.1'].includes(window.location.hostname)?`${window.location.protocol==='https:'?'wss':'ws'}://${window.location.host}/ws`:DEFAULT_SERVER_URL;
const powerIcon=(id:string,size=22)=>id==='openclaw'?<Sparkles size={size}/>:id==='hermes'?<Zap size={size}/>:id==='opencode'?<Terminal size={size}/>:id==='codex'?<RotateCcw size={size}/>:id==='cline'?<SkipForward size={size}/>:id==='roo'?<AudioLines size={size}/>:<Shield size={size}/>;
const clock=(t:number)=>`${Math.floor(Math.max(0,t)/60).toString().padStart(2,'0')}:${Math.floor(Math.max(0,t)%60).toString().padStart(2,'0')}`;
export default function Home(){
 const canvas=useRef<HTMLCanvasElement>(null),runtime=useRef<any>(null),modeRef=useRef<Mode>('selection');
 const [mode,setMode]=useState<Mode>('selection'),[character,setCharacter]=useState('chatgpt'),[harness,setHarness]=useState('openclaw'),[mapId,setMapId]=useState('exchange'),[ready,setReady]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[hud,setHud]=useState<any>(null),[scores,setScores]=useState(false),[sensitivity,setSensitivity]=useState(1),[muted,setMuted]=useState(false),[settings,setSettings]=useState(false),[pointerHint,setPointerHint]=useState(false),[netUrl,setNetUrl]=useState(defaultNetUrl),[netPlayers,setNetPlayers]=useState<any[]>([]),[netError,setNetError]=useState('');
 const [config,setConfig]=useState<any>({...DEFAULT_CONFIG}),[display,setDisplay]=useState<any>({...DEFAULT_DISPLAY}),[rooms,setRooms]=useState<any[]>([]),[matches,setMatches]=useState<any[]>([]),[roomName,setRoomName]=useState(''),[netRoomId,setNetRoomId]=useState('');
 const [chatOpen,setChatOpen]=useState(false),[chatDraft,setChatDraft]=useState(''),[chatLog,setChatLog]=useState<any[]>([]);
 const chatInputRef=useRef<HTMLInputElement>(null);
 const selectedMode=GAME_MODES.find(m=>m.id===config.mode)!;
 const selectedMap=getMap(mapId);
 const selected=CHARACTERS.find((c:any)=>c.id===character)!,power=HARNESSES.find((h:any)=>h.id===harness)!;
 const myPeerId=runtime.current?.net?.peerId;
 const changeMode=(m:Mode)=>{modeRef.current=m;setMode(m);setChatOpen(false);if(runtime.current){runtime.current.keys.clear();runtime.current.fire=false;runtime.current.fireTap=false;runtime.current.jump=false;runtime.current.power=false;runtime.current.acc=0;}setScores(false);};
 useEffect(()=>{let cancelled=false,raf=0;const keys=new Set<string>();let view:any,audio:any;let resize:()=>void=()=>{};
 (async()=>{try{const module=await import('../game/view.mjs');if(cancelled)return;view=new module.ArenaView(canvas.current);audio=new module.SynthAudio();const r:any={view,audio,keys,match:null,fire:false,fireTap:false,jump:false,power:false,acc:0,lastAudio:0,lookSensitivity:1,hadLock:false,drag:false,fps:0,frames:0,sample:performance.now(),lastDamage:-10,lastHit:-10,pickupText:'',pickupAt:-10,net:null,netViewReady:false,renderState:null,look:{yaw:0,pitch:0},inputWeapon:-1};runtime.current=r;modeRef.current='selection';setMode('selection');setHud(null);
 try{const saved=JSON.parse(localStorage.getItem('token-arena-customization')||'{}');setConfig(normalizeConfig(saved.config));setDisplay(normalizeDisplay(saved.display));if(MAPS.some(m=>m.id===saved.mapId))setMapId(saved.mapId);}catch{}
 try{const prefs=JSON.parse(localStorage.getItem('token-arena-settings')||'{}');if(typeof prefs.sensitivity==='number'){r.lookSensitivity=Math.max(.3,Math.min(2.5,Number.isFinite(prefs.sensitivity)?prefs.sensitivity:1));setSensitivity(r.lookSensitivity);}if(typeof prefs.muted==='boolean'){audio.muted=prefs.muted;setMuted(prefs.muted);}}catch{}
 resize=()=>view.resize();window.addEventListener('resize',resize);let last=performance.now(),hudAt=0;
 const loop=(now:number)=>{if(cancelled)return;const elapsed=Math.min(.1,(now-last)/1000);last=now;r.frames++;if(now-r.sample>=1000){r.fps=Math.round(r.frames*1000/(now-r.sample));r.frames=0;r.sample=now;}
  if(modeRef.current==='playing'&&r.net?.started&&!r.net.roundOver){
  r.acc=Math.min(r.acc+elapsed,RULES.dt*5);let guard=0;
  if(!r.net.spectate){while(r.acc>=RULES.dt&&guard<5){r.acc-=RULES.dt;guard++;
   const p=r.look,forward=(keys.has('KeyW')?1:0)-(keys.has('KeyS')?1:0),right=(keys.has('KeyD')?1:0)-(keys.has('KeyA')?1:0);
   const input:any={x:-Math.sin(p.yaw)*forward+Math.cos(p.yaw)*right,z:-Math.cos(p.yaw)*forward-Math.sin(p.yaw)*right,yaw:p.yaw,pitch:p.pitch,fire:r.fire||r.fireTap};
   if(r.jump)input.jump=true;if(r.power)input.power=true;
   if(r.inputWeapon>=0){input.weapon=r.inputWeapon;r.inputWeapon=-1;}
   r.net.input(input);r.net.predict(input);r.fireTap=false;r.jump=false;r.power=false;
  }}
  const s=r.net.renderState(performance.now());
  if(s){if(!r.netViewReady){r.view.setMatch(r.net.viewMatch());r.view.lastEvent=0;r.view.setSpectator(r.net.spectate);r.view.setPlayerId(r.net.actorId??-1);r.netViewReady=true;}r.renderState=s;
   const me=s.actors.find((a:any)=>a.id===r.net.actorId)||s.actors[0];
   for(const e of r.net.events)if(e.id>r.lastAudio){audio.event(e,me);if(e.type==='damage'&&e.actor===r.net.actorId)r.lastDamage=s.time;if(e.type==='damage'&&e.source===r.net.actorId&&e.actor!==r.net.actorId)r.lastHit=s.time;if(e.type==='pickup'&&e.actor===r.net.actorId){r.pickupText=`${e.kind.toUpperCase()} ACQUIRED`;r.pickupAt=s.time;}r.lastAudio=e.id;}
   view.render(modeRef.current,s,elapsed,now/1000);
   if(now-hudAt>80){setHud({...s,net:true,actorId:r.net.actorId,spectate:r.net.spectate,damage:s.time-r.lastDamage<.25,hit:s.time-r.lastHit<.12,pickup:s.time-r.pickupAt<1.5?r.pickupText:'',fps:r.fps,renderer:view.renderer.isSoftware?'software':'webgl',pointerLocked:!!document.pointerLockElement});hudAt=now;}
  }
  }
 else if(modeRef.current==='playing'&&r.match){r.acc=Math.min(r.acc+elapsed,RULES.dt*5);while(r.acc>=RULES.dt){const p=r.match.actors[0],forward=(keys.has('KeyW')?1:0)-(keys.has('KeyS')?1:0),right=(keys.has('KeyD')?1:0)-(keys.has('KeyA')?1:0);r.match.step(RULES.dt,{x:-Math.sin(p.yaw)*forward+Math.cos(p.yaw)*right,z:-Math.cos(p.yaw)*forward-Math.sin(p.yaw)*right,fire:r.fire||r.fireTap,jump:r.jump,power:r.power});r.fireTap=false;r.jump=false;r.power=false;r.acc-=RULES.dt;if(r.match.over){changeMode('results');document.exitPointerLock?.();audio.tone(520,.4,'sine',.05,1000);break;}}
 for(const e of r.match.events)if(e.id>r.lastAudio){audio.event(e,r.match.actors[0]);if(e.type==='damage'&&e.actor===0)r.lastDamage=r.match.time;if(e.type==='damage'&&e.source===0&&e.actor!==0)r.lastHit=r.match.time;if(e.type==='pickup'&&e.actor===0){r.pickupText=`${e.kind.toUpperCase()} ACQUIRED`;r.pickupAt=r.match.time;}r.lastAudio=e.id;}}
 view.render(modeRef.current,r.match??(r.net?.started?r.renderState:null),modeRef.current==='playing'?elapsed:0,now/1000);
 if(r.match&&now-hudAt>80){setHud({...r.match.snapshot(),damage:r.match.time-r.lastDamage<.25,hit:r.match.time-r.lastHit<.12,pickup:r.match.time-r.pickupAt<1.5?r.pickupText:'',fps:r.fps,renderer:view.renderer.isSoftware?'software':'webgl',pointerLocked:!!document.pointerLockElement});hudAt=now;}raf=requestAnimationFrame(loop);};raf=requestAnimationFrame(loop);setReady(true);
 (window as any).tokenArenaSnapshot=()=>({mode:modeRef.current,fps:r.fps,renderer:view.renderer.isSoftware?'software':'webgl',drawCalls:view.renderer.info.render.calls,triangles:view.renderer.info.render.triangles,pointerLocked:!!document.pointerLockElement,...(r.match?.snapshot()??r.renderState??{})});
 }catch(e:any){setError(`The 3D renderer could not start: ${e.message}. Try a desktop browser with WebGL enabled.`);}})();
 const keydown=(e:KeyboardEvent)=>{const r=runtime.current;if(!r)return;if(modeRef.current==='playing'){if(document.activeElement?.tagName==='INPUT')return;if((e.code==='KeyT'||e.code==='Enter')&&r.net?.started){setChatOpen(true);e.preventDefault();return;}if(['Space','Tab','Escape','KeyW','KeyA','KeyS','KeyD'].includes(e.code))e.preventDefault();if(e.code==='Escape'){if(r.net?.started){changeMode('lobby');document.exitPointerLock?.();return;}changeMode('paused');document.exitPointerLock?.();return;}if(e.code==='Tab')setScores(true);keys.add(e.code);if(e.code==='Space'&&!e.repeat)r.jump=true;if(e.code==='KeyQ'&&!e.repeat)r.power=true;if(/^Digit[1-5]$/.test(e.code)){const n=Number(e.code.slice(-1))-1;if(r.net?.started)r.inputWeapon=n;else if(r.match.actors[0].ammo[n]>0)r.match.actors[0].weapon=n;}}};
 const keyup=(e:KeyboardEvent)=>{keys.delete(e.code);if(e.code==='Tab')setScores(false);};
 const move=(e:MouseEvent)=>{const r=runtime.current;if(modeRef.current!=='playing'||!r?.match&&!r?.net?.started||(!document.pointerLockElement&&!r.drag))return;const look=r.net?.started?r.look:r.match.actors[0];look.yaw-=e.movementX*.002*r.lookSensitivity;look.pitch=Math.max(-1.45,Math.min(1.45,look.pitch-e.movementY*.002*r.lookSensitivity));};
 const down=(e:MouseEvent)=>{if(e.target!==canvas.current||modeRef.current!=='playing')return;const r=runtime.current;if(e.button===0){r.fire=true;r.fireTap=true;}r.drag=true;};
 const up=()=>{if(runtime.current){runtime.current.fire=false;runtime.current.drag=false;}};
 const pause=()=>{if(modeRef.current==='playing'){if(runtime.current?.net?.started){document.exitPointerLock?.();}else changeMode('paused');document.exitPointerLock?.();}};
 const lock=()=>{const r=runtime.current;if(!r)return;if(document.pointerLockElement){r.hadLock=true;setPointerHint(false);}else if(r.hadLock){r.hadLock=false;if(!r.net?.started)pause();}};
 const wheel=(e:WheelEvent)=>{const r=runtime.current;if(modeRef.current!=='playing'||e.target!==canvas.current||(!r?.match&&!r?.net?.started))return;e.preventDefault();if(r.net?.started){const me=r.renderState?.actors.find((a:any)=>a.id===r.net.actorId);if(!me)return;let n=me.weapon;for(let i=0;i<WEAPONS.length;i++){n=(n+(e.deltaY>0?1:WEAPONS.length-1))%WEAPONS.length;if(me.ammo[n]>0){r.inputWeapon=n;break;}}return;}const p=r.match.actors[0];let n=p.weapon;for(let i=0;i<WEAPONS.length;i++){n=(n+(e.deltaY>0?1:WEAPONS.length-1))%WEAPONS.length;if(p.ammo[n]>0){p.weapon=n;break;}}};
 window.addEventListener('keydown',keydown);window.addEventListener('keyup',keyup);window.addEventListener('mousemove',move);window.addEventListener('mousedown',down);window.addEventListener('mouseup',up);window.addEventListener('blur',pause);document.addEventListener('pointerlockchange',lock);window.addEventListener('wheel',wheel,{passive:false});
 return()=>{cancelled=true;cancelAnimationFrame(raf);window.removeEventListener('resize',resize);window.removeEventListener('keydown',keydown);window.removeEventListener('keyup',keyup);window.removeEventListener('mousemove',move);window.removeEventListener('mousedown',down);window.removeEventListener('mouseup',up);window.removeEventListener('blur',pause);document.removeEventListener('pointerlockchange',lock);window.removeEventListener('wheel',wheel);view?.dispose();audio?.dispose();runtime.current?.net?.close();delete (window as any).tokenArenaSnapshot;runtime.current=null;};
 },[]);
 useEffect(()=>{runtime.current?.view.setCharacter(character);},[character,ready]);
 useEffect(()=>{runtime.current?.view.setDisplay(display);},[display,ready]);
 useEffect(()=>{if(ready)try{localStorage.setItem('token-arena-customization',JSON.stringify({config,display,mapId}));}catch{}},[config,display,mapId,ready]);
 const saveSettings=(s:number,m:boolean)=>{setSensitivity(s);setMuted(m);if(runtime.current){runtime.current.lookSensitivity=s;runtime.current.audio.muted=m;}try{localStorage.setItem('token-arena-settings',JSON.stringify({sensitivity:s,muted:m}));}catch{}};
 const requestLock=()=>{try{const result=canvas.current?.requestPointerLock();result?.catch(()=>setPointerHint(true));}catch{setPointerHint(true);}};
  const wireNet=(n:any)=>{const r=runtime.current;n.onStart=()=>{r.netViewReady=false;r.lastAudio=0;r.lastDamage=r.lastHit=r.pickupAt=-10;r.acc=0;r.audio.start();changeMode('playing');if(!n.spectate)requestLock();};
  n.onResults=(m:any)=>{document.exitPointerLock?.();setHud({...m.state,net:true,actorId:r.net?.actorId,fps:r.fps,renderer:r.view.renderer.isSoftware?'software':'webgl',pointerLocked:false,damage:false,hit:false,pickup:''});changeMode('results');};
  n.onClose=()=>{if(r.net!==n)return;setNetPlayers([]);setNetError('Connection lost. Your seat is held briefly — reconnect to return.');changeMode('lobby');};
  n.onError=(m:any)=>setNetError(m.message);
  n.onLobby=(m:any)=>{setNetPlayers(m.players);setNetRoomId(m.roomId);setNetError('');};
  n.onRooms=(m:any)=>setRooms(m.rooms);
  n.onHistory=(m:any)=>setMatches(m.matches);
  n.onChat=(m:any)=>setChatLog(prev=>[...prev.slice(-99),m]);};
  const connectNet=async()=>{const r=runtime.current;if(!r)return;if(r.net?.connected){r.net.close();r.net=null;setNetPlayers([]);setNetError('');changeMode('selection');return;}
  const n=new NetClient(netUrl.trim()||DEFAULT_SERVER_URL);r.net=n;wireNet(n);
  try{await n.connect();n.join(config.playerName||selected.name,character,harness);changeMode('lobby');}catch(e:any){setNetError(String(e?.message||e));if(r.net===n){r.net=null;n.close();}}
  };
  const openBrowser=async()=>{const r=runtime.current;if(!r)return;const n=r.net&&r.net.connected?r.net:new NetClient(netUrl.trim()||DEFAULT_SERVER_URL);if(r.net!==n){r.net=n;wireNet(n);}try{if(!n.connected)await n.connect();}catch(e:any){setNetError(String(e?.message||e));return;}n.list();n.history();changeMode('browse');};
  const joinRoom=(roomId:string,spectate:boolean)=>{const r=runtime.current,n=r?.net;if(!r||!n?.connected)return;setNetError('');if(n.players.length>0)n.leave();n.join(config.playerName||selected.name,character,harness,{roomId,spectate});changeMode('lobby');};
  const createRoom=()=>{const r=runtime.current,n=r?.net;if(!r||!n?.connected)return;setNetError('');if(n.players.length>0)n.leave();n.create(roomName.trim()||'Custom',character,harness,config.playerName||selected.name);n.list();changeMode('lobby');};
  const sendChat=()=>{const n=runtime.current?.net;if(!n?.connected||!chatDraft.trim())return;n.chat(chatDraft);setChatDraft('');};
 const reconnectNet=async()=>{const r=runtime.current;const n=r?.net;if(!n)return;setNetError('');try{await n.connect(n.url);n.join(config.playerName||selected.name,character,harness);}catch(e:any){setNetError(String(e?.message||e));}};
 const resumeNet=()=>{changeMode('playing');requestLock();};
 const disconnectNet=()=>{const r=runtime.current;if(!r?.net)return;r.net.leave();r.net.close();r.net=null;setNetPlayers([]);setNetError('');changeMode('selection');};
 const hostAndStart=()=>{const r=runtime.current;if(!r?.net?.connected)return;r.net.host(config,mapId);r.net.start();};
 const start=()=>{const r=runtime.current;if(!r)return;const loadout=resolveLoadout(character,harness);r.match=new Match(loadout.character,loadout.harness,Math.random,mapId,config);r.view.setMatch(r.match);r.lastAudio=0;r.lastDamage=r.lastHit=r.pickupAt=-10;r.audio.start();setHud(r.match.snapshot());changeMode('playing');requestLock();};
 const resume=()=>{runtime.current?.audio.start();changeMode('playing');requestLock();};
 const chooseCharacter=(id:string)=>{setCharacter(id);const valid=resolveLoadout(id,harness);if(valid.harness!==harness){setHarness(valid.harness);setNotice('Claude equipped Claude Code automatically.');}else setNotice('');};
 const prefs=<><div className="preferences"><label htmlFor="sensitivity">Mouse sensitivity <span>{sensitivity.toFixed(1)}×</span></label><Slider id="sensitivity" aria-label="Mouse sensitivity" value={[sensitivity]} min={.3} max={2.5} step={.1} onValueChange={([v])=>saveSettings(v,muted)}/><div className="sound-setting"><label htmlFor="audio-switch">Game audio</label><Switch id="audio-switch" checked={!muted} onCheckedChange={v=>saveSettings(sensitivity,!v)}/></div></div><DisplayConfiguration display={display} onChange={(v:any)=>setDisplay(normalizeDisplay(v))}/></>;
 const player=hud?.actors?.find((a:any)=>a.id===(hud.actorId??0))||hud?.actors?.[0],sorted=hud?.actors?[...hud.actors].sort((a:any,b:any)=>b.frags-a.frags||a.deaths-b.deaths):[],activePower=HARNESSES.find((h:any)=>h.id===player?.harness);
 const scoreboard=<div className="scoreboard"><div className="score-row labels"><span>OPERATOR</span><span>FRAGS</span><span>DEATHS</span></div>{sorted.map((a:any,i:number)=><div className={`score-row ${a.id===(hud?.actorId??0)?'you':''}`} key={a.id}><span><b>{String(i+1).padStart(2,'0')}</b><i style={{background:CHARACTERS.find((c:any)=>c.id===a.character)?.color}}/>{a.name}{(a.id===(hud?.actorId??0))&&<small>YOU</small>}</span><strong>{a.frags}</strong><span>{a.deaths}</span></div>)}</div>;
 return <main className={`arena-app mode-${mode}`}>
 <canvas ref={canvas} className="arena-canvas" aria-label="TOKEN ARENA 3D game" data-snapshot={JSON.stringify({mode,...hud})}/>
 {mode==='selection'&&<div className="selection-screen">
 <header className="topbar"><div className="wordmark"><Crosshair size={25}/><span>TOKEN<span className="wordmark-light">ARENA</span></span><small>CUSTOM MATCH / 03</small></div><div className="header-right"><span className="local-label">LOCAL ARENA</span><button className="icon-button" aria-label={muted?'Unmute audio':'Mute audio'} onClick={()=>saveSettings(sensitivity,!muted)}>{muted?<VolumeX size={19}/>:<Volume2 size={19}/>}</button></div></header>
 <div className="selection-heading"><p className="eyebrow"><span className="accent-line"/> LOADOUT CONFIGURATION</p><h1>Choose your intelligence<span>.</span></h1><p>Nine minds. Three arenas. No consensus.</p></div>
 <div className="loadout-grid">
 <section className="roster-panel"><div className="section-label"><span>01 / OPERATOR</span><span>{CHARACTERS.length} AVAILABLE</span></div><div className="roster">{CHARACTERS.map((c:any,i:number)=><button key={c.id} className={`operator-card ${character===c.id?'selected':''}`} style={{'--operator':c.color} as any} onClick={()=>chooseCharacter(c.id)} aria-pressed={character===c.id}><span className="operator-symbol"><Hexagon size={27} strokeWidth={1.3}/><span>{c.name.slice(0,1)}</span></span><span className="operator-name">{c.name}<small>{c.tag}</small></span><span className="operator-number">{character===c.id?<Check size={18}/>:String(i+1).padStart(2,'0')}</span></button>)}</div><div className="equal-stats"><span><b>100</b> HEALTH</span><span><b>{8*config.speed}</b> SPEED</span><span><b>{WEAPONS.length}</b> WEAPONS</span></div><p className="roster-note">Same base stats. Your harness changes the fight.</p></section>
 <section className="operator-preview" aria-label={`${selected.name} animated 3D model`}><span className="preview-corner">LIVE MODEL / {String(CHARACTERS.indexOf(selected)+1).padStart(2,'0')}</span><div className="operator-caption"><p className="eyebrow" style={{color:selected.color}}>{selected.tag}</p><h2>{selected.name}</h2><p>{selected.detail}</p></div></section>
 <section className="harness-panel"><div className="section-label"><span>02 / HARNESS</span><span>ACTIVE ABILITY</span></div><div className="harness-list">{HARNESSES.map((h:any)=>{const locked=character==='claude'&&h.id!=='claudecode';return <button className={`harness-card ${harness===h.id?'selected':''}`} key={h.id} onClick={()=>{setHarness(h.id);setNotice('');}} disabled={locked} aria-pressed={harness===h.id}><span className="harness-icon">{powerIcon(h.id)}</span><span><strong>{h.name}</strong><small>{h.power}</small></span>{locked?<LockKeyhole size={15}/>:harness===h.id?<Check size={17}/>:<span className="harness-key">{h.key}</span>}</button>;})}</div><div className="ability-detail"><div><span className="eyebrow">{power.power}</span><span className="keycap">Q</span></div><p>{power.description}</p><footer><span>{power.stat}</span><span>{power.cooldown}s COOLDOWN</span></footer></div><div className="compatibility-note">{notice||(character==='claude'?'Claude requires Claude Code.':'Compatible with all seven harnesses.')}</div><button className="text-button setup-shortcut" onClick={()=>document.getElementById('match-setup')?.scrollIntoView({block:'start'})}>MODE & BOT SETTINGS ↓</button><button className="deploy-button" onClick={start} disabled={!ready||!!error}><span>{ready?'ENTER ARENA':'INITIALIZING ARENA'}<small>{selectedMode.name.toUpperCase()} · {config.botCount} BOTS</small></span><ArrowUpRight size={26}/></button></section>
 </div>
 <section className="map-selection"><div className="section-label"><span>03 / ARENA</span><span>{selectedMap.tag}</span></div> <RadioGroup className="map-options" value={mapId} onValueChange={setMapId} aria-label="Arena selection">{MAPS.map((map:any)=><label htmlFor={`map-${map.id}`} key={map.id} className={`map-option ${mapId===map.id?'selected':''}`} style={{'--map-color':map.color} as any}><svg className="map-plan" viewBox="-15 -15 30 30" aria-hidden="true"><rect x="-15" y="-15" width="30" height="30" fill="#0a1218"/>{map.blocks.map((b:any,i:number)=><rect key={i} x={b.x-b.w/2} y={b.z-b.d/2} width={b.w} height={b.d} fill={b.kind==='wall'?'#4c6469':map.color} opacity={b.kind==='deck'?.25:.8}/> )}</svg><div><strong>{map.name}</strong><small>{map.description}</small></div><RadioGroupItem id={`map-${map.id}`} value={map.id} aria-label={map.name}/></label>)}</RadioGroup></section>
  <section className="online-panel"><div className="section-label"><span>04 / MULTIPLAYER</span><span>LOCAL SERVER</span></div><div className="online-row"><input className="server-input" value={netUrl} onChange={e=>setNetUrl(e.target.value)} placeholder="ws://host:port" aria-label="Game server address" spellCheck={false}/><button className="secondary-button" onClick={connectNet} disabled={!ready||!!error}>{runtime.current?.net?.connected?<><span>DISCONNECT</span><LockKeyhole size={15}/></>:<><span>CONNECT & JOIN</span><ArrowUpRight size={15}/></>}</button></div><div className="online-row"><button className="secondary-button" onClick={openBrowser} disabled={!ready||!!error}><span>ROOM BROWSER</span><ArrowUpRight size={15}/></button><p className="roster-note browse-note">Browse concurrent rooms, join as player or WATCH as spectator, or create a room with a shareable 4-letter code. The first player to join a room becomes host.</p></div><p className="roster-note">Host a match on this machine and play over the local network. The server is authoritative.</p>{netError&&<p className="net-error" role="alert">{netError}</p>}</section>
 <MatchConfiguration config={config} onChange={(v:any)=>setConfig({...normalizeConfig(v),playerName:v.playerName})}/>
 <footer className="selection-footer"><div className="map-info"><span className="map-icon"><Crosshair size={23}/></span><div><small>{selectedMap.name.toUpperCase()}</small><strong>{config.fragLimit} frags <span>/</span> {config.timeLimit/60} minutes <span>/</span> {config.botCount} bots</strong></div></div><div className="controls-brief"><span><kbd>W A S D</kbd> Move</span><span><kbd>SPACE</kbd> Jump</span><span><kbd>Q</kbd> Power</span><button onClick={()=>setSettings(!settings)}>CONTROLS & SETTINGS <ChevronRight size={14}/></button></div></footer>
 {settings&&<div className="settings-panel"><button className="text-button close-settings" onClick={()=>setSettings(false)}>CLOSE ×</button><h3>Controls & settings</h3><div className="arsenal-list">{WEAPONS.map((w:any,i:number)=><span key={w.name} style={{color:w.color}}>{i+1} / {w.name}</span>)}</div><div className="control-list"><span>Mouse</span><span>Look / left click to fire</span><span>WASD / Space</span><span>Move / jump</span><span>1–5 / Wheel</span><span>Switch weapon</span><span>Q / Tab / Escape</span><span>Power / scores / pause</span></div>{prefs}</div>}
  <p className="desktop-note">Keyboard and mouse required. Open on desktop to play.</p>
  </div>}
  {mode==='browse'&&<div className="selection-screen browse-screen">
  <header className="topbar"><div className="wordmark"><Crosshair size={25}/><span>TOKEN<span className="wordmark-light">ARENA</span></span><small>ROOM BROWSER</small></div><div className="header-right"><span className="local-label">{netUrl}</span><button className="icon-button" aria-label={muted?'Unmute audio':'Mute audio'} onClick={()=>saveSettings(sensitivity,!muted)}>{muted?<VolumeX size={19}/>:<Volume2 size={19}/>}</button></div></header>
  <div className="selection-heading"><p className="eyebrow"><span className="accent-line"/> CONCURRENT ROOMS</p><h1>Pick a fight<span>.</span></h1><p>Join any open room, watch one in progress, or create your own code.</p></div>
  <div className="loadout-grid">
  <section className="roster-panel"><div className="section-label"><span>ROOMS</span><span>{rooms.filter((r:any)=>r.started||r.players>0).length} LIVE</span></div><div className="roster">{rooms.map((room:any)=>{const map=MAPS.find((m:any)=>m.id===room.mapId);return <div key={room.roomId} className="operator-card room-card" style={{'--operator':map?.color} as any}><span className="operator-symbol"><Hexagon size={27} strokeWidth={1.3}/><span>{room.roomId.slice(0,1)}</span></span><span className="operator-name">{room.name||room.roomId}<small>{room.started?`IN MATCH · ${map?.name??room.mapId}`:room.players>0?'LOBBY OPEN':'EMPTY'}</small></span><span className="operator-number">{room.players}P</span><span className="room-actions"><button className="secondary-button" onClick={()=>joinRoom(room.roomId,false)} disabled={room.started&&room.players>0}><span>{room.started?'SPECTATE':'JOIN'}</span><ArrowUpRight size={13}/></button><button className="secondary-button watch-button" onClick={()=>joinRoom(room.roomId,true)}><span>WATCH</span><Crosshair size={13}/></button></span></div>;})}{rooms.length===0&&<p className="roster-note">No rooms yet. Create one below — the first player to join becomes host.</p>}</div><button className="secondary-button" onClick={()=>{runtime.current?.net?.list();runtime.current?.net?.history();}}><span>REFRESH</span><RotateCcw size={15}/></button><button className="secondary-button" onClick={()=>changeMode('selection')}><span>BACK</span><ChevronRight size={15}/></button></section>
  <section className="harness-panel"><div className="section-label"><span>CREATE ROOM</span><span>4-LETTER CODE</span></div><div className="online-row"><input className="server-input" value={roomName} onChange={e=>setRoomName(e.target.value)} placeholder="Room name" aria-label="Room name" spellCheck={false}/><button className="deploy-button create-button" onClick={createRoom}><span>CREATE & HOST<small>YOU WILL BE THE HOST</small></span><ArrowUpRight size={20}/></button></div><p className="roster-note">A room gets a short code others can type or click. Any player can host a rematch; the room persists while players are inside.</p><div className="section-label"><span>RECENT MATCHES</span><span>{matches.length} RECORDED</span></div><div className="scoreboard history-board">{matches.slice(0,6).map((m:any)=><div className="history-match" key={m.id}><div className="score-row labels"><span>{m.mode.toUpperCase()} · {m.mapId.toUpperCase()} · {m.endedBy.toUpperCase()} · {m.duration.toFixed(0)}s</span><span>WINNER</span></div>{m.players.slice(0,4).map((p:any,i:number)=><div className="score-row" key={`${m.id}-${i}`}><span><b>{String(i+1).padStart(2,'0')}</b><i style={{background:CHARACTERS.find((c:any)=>c.id===p.character)?.color}}/>{p.name}</span><strong>{p.frags}</strong><span>{p.deaths}</span></div>)}<p className="history-leader">{m.leader} <small>LEADS · ROOM {m.roomId}</small></p></div>)}</div>{matches.length===0&&<p className="roster-note">No completed matches on this server yet.</p>}{netError&&<p className="net-error" role="alert">{netError}</p>}</section>
  </div>
  </div>}
  {mode==='lobby'&&<div className="selection-screen lobby-screen">
  <header className="topbar"><div className="wordmark"><Crosshair size={25}/><span>TOKEN<span className="wordmark-light">ARENA</span></span><small>{netRoomId?`ROOM ${netRoomId}`:'NETWORK LOBBY'}</small></div><div className="header-right"><span className="local-label">{netUrl}</span><button className="icon-button" aria-label={muted?'Unmute audio':'Mute audio'} onClick={()=>saveSettings(sensitivity,!muted)}>{muted?<VolumeX size={19}/>:<Volume2 size={19}/>}</button></div></header>
  <div className="selection-heading"><p className="eyebrow"><span className="accent-line"/> PLAYERS ONLINE</p><h1>Gather at the server<span>.</span></h1><p>First to join hosts the match. Escape during play returns here.</p></div>
  <div className="loadout-grid">
  <section className="roster-panel"><div className="section-label"><span>01 / PLAYERS</span><span>{netPlayers.length} CONNECTED</span></div> <div className="roster">{netPlayers.map((p:any,i:number)=><div key={p.peerId} className={`operator-card ${p.peerId===myPeerId?'selected':''}`} style={{'--operator':CHARACTERS.find((c:any)=>c.id===p.character)?.color} as any}><span className="operator-symbol"><Hexagon size={27} strokeWidth={1.3}/><span>{p.name.slice(0,1)}</span></span><span className="operator-name">{p.name}<small>{p.spectate?'SPECTATOR':p.connected===false?'DISCONNECTED · SEAT HELD':p.peerId===runtime.current?.net?.hostId?'HOST':p.actorId!==null?'IN MATCH':'READY'}</small></span><span className="operator-number">{p.spectate?'WATCH':p.connected===false?'…':p.actorId!==null?`A${p.actorId}`:String(i+1).padStart(2,'0')}</span></div>)}</div><p className="roster-note">Your actor stays in the match if you leave; it idles until the next start.</p>
  <div className="lobby-chat"><div className="section-label"><span>CHAT</span><span>ROOM ONLY</span></div><div className="chat-lines">{chatLog.slice(-30).map((m:any,i:number)=><div key={i}><b>{m.name}</b>{m.text}</div>)}</div><div className="online-row"><input className="server-input" value={chatDraft} onChange={e=>setChatDraft(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')sendChat();}} placeholder="Message the room…" aria-label="Chat message" spellCheck={false}/><button className="secondary-button chat-send" onClick={sendChat}><span>SEND</span><ArrowUpRight size={13}/></button></div></div>
  </section>
 <section className="harness-panel"><div className="section-label"><span>02 / HOST CONTROLS</span><span>{runtime.current?.net?.connected?runtime.current?.net?.isHost?'YOU ARE HOST':'WAITING ON HOST':'OFFLINE'}</span></div>
  {!runtime.current?.net?.connected?<><p className="net-error" role="alert">{netError||'Connection lost.'}</p><button className="deploy-button" onClick={reconnectNet}><span>RECONNECT<small>REJOIN YOUR SEAT IF STILL HELD</small></span><Play size={20}/></button></>
  :runtime.current?.net?.spectate?<>
  <p className="roster-note">Watching this room as a <b>spectator</b>. You will follow live actors once the match runs — no firing arm, no seat.</p>
  {runtime.current?.net?.started&&!runtime.current?.net?.roundOver?<button className="deploy-button" onClick={resumeNet}><span>WATCHING MATCH<small>CLICK TO ENTER SPECTATOR VIEW</small></span><Play size={20}/></button>:<p className="roster-note">Waiting for the host to start. You will see snapshots automatically.</p>}</>
  :runtime.current?.net?.isHost?<>
 <MatchConfiguration config={config} onChange={(v:any)=>setConfig({...normalizeConfig(v),playerName:v.playerName})}/><div className="section-label"><span>ARENA</span><span>{selectedMap.tag}</span></div><RadioGroup className="map-options" value={mapId} onValueChange={setMapId} aria-label="Arena selection">{MAPS.map((map:any)=><label htmlFor={`net-map-${map.id}`} key={map.id} className={`map-option ${mapId===map.id?'selected':''}`} style={{'--map-color':map.color} as any}><svg className="map-plan" viewBox="-15 -15 30 30" aria-hidden="true"><rect x="-15" y="-15" width="30" height="30" fill="#0a1218"/>{map.blocks.map((b:any,i:number)=><rect key={i} x={b.x-b.w/2} y={b.z-b.d/2} width={b.w} height={b.d} fill={b.kind==='wall'?'#4c6469':map.color} opacity={b.kind==='deck'?.25:.8}/> )}</svg><div><strong>{map.name}</strong><small>{map.description}</small></div><RadioGroupItem id={`net-map-${map.id}`} value={map.id} aria-label={map.name}/></label>)}</RadioGroup><button className="deploy-button" onClick={hostAndStart} disabled={!runtime.current?.net?.connected}><span>START NETWORK MATCH<small>{selectedMode.name.toUpperCase()} · {config.botCount} BOTS · {netPlayers.length} PLAYERS</small></span><ArrowUpRight size={26}/></button></>
  :runtime.current?.net?.started&&(runtime.current?.net?.actorId!==null||runtime.current?.net?.spectate)&&!runtime.current?.net?.roundOver?<>
  <p className="roster-note">A match is in progress and your seat is held. Resume to keep playing.</p>
  <button className="deploy-button" onClick={resumeNet}><span>RESUME MATCH<small>{runtime.current?.net?.spectate?'SPECTATOR VIEW':'SEAT HELD · RETURN TO ARENA'}</small></span><Play size={20}/></button></>
 :<p className="roster-note">Waiting for the host to choose match settings and start. You will be placed automatically.</p>}
 {netError&&runtime.current?.net?.connected&&<p className="net-error" role="alert">{netError}</p>}
 {runtime.current?.net?.connected&&<button className="secondary-button" onClick={disconnectNet}><span>DISCONNECT</span><LockKeyhole size={15}/></button>}
 </section>
 </div>
 </div>}
 {error&&<div className="error-banner" role="alert">{error}</div>}
 {(mode==='playing'||mode==='paused')&&player&&<>
  <div className="game-hud"><div className="match-top"><div><span className="eyebrow">{hud.mapName?.toUpperCase()}</span><strong>{hud.modeName?.toUpperCase()}</strong></div><div className="match-clock">{hud.spectate?'SPECTATING':clock(hud.config.timeLimit-hud.time)}<small>{hud.net?'NETWORK MATCH':hud.config.botCount===0?'SOLO PRACTICE':`FIRST TO ${hud.config.fragLimit}`}</small></div><div className="frag-counter"><strong>{player.frags}<span>{hud.spectate?'':` / ${hud.config.fragLimit}`}</span></strong><small>{hud.spectate?`FOLLOWING ${player.name.toUpperCase()}`:'YOUR FRAGS'}</small></div></div>
  <div className="kill-feed">{(runtime.current?.match||runtime.current?.renderState)?.feed.filter((e:any)=>hud.time-e.time<6).map((e:any,i:number)=><div key={`${e.time}-${i}`}><span>{e.killer}</span><Crosshair size={12}/><span>{e.victim}</span>{e.self&&<small>SELF</small>}</div>)}</div>
  {hud.spectate?<div className="spectator-tag"><span className="eyebrow">SPECTATOR MODE</span><h2>NO SEAT</h2><p>Camera follows {player.name} live. Snapshot feed only — no inputs sent.</p></div>:player.health>0?<div className={`crosshair shape-${display.crosshair} ${hud.hit?'hit':''}`} style={{'--crosshair-color':display.color,'--crosshair-size':display.size} as any}><span/><span/><span/><span/></div>:<div className="death-message"><span className="eyebrow">CONNECTION LOST</span><h2>RECOMPILING</h2><p>Respawning in {Math.max(1,Math.ceil(player.dead))}…</p></div>}
  {hud.damage&&!hud.spectate&&<div className="damage-vignette"/>}
  <div className="pickup-message">{player.slow>0?`CONTEXT JAM · ${player.slow.toFixed(1)}s`:hud.pickup}</div>
  {player.protection>0&&player.health>0&&!hud.spectate&&<div className="spawn-protection"><Shield size={15}/> SPAWN PROTECTION</div>}
  {pointerHint&&mode==='playing'&&!hud.spectate&&<div className="pointer-hint">Mouse capture unavailable here. Hold left mouse to aim and fire. <button onClick={requestLock}>Retry capture</button></div>}
  <div className="bottom-hud"><div className="vitals"><div className="health"><span>+</span><strong>{Math.ceil(player.health)}</strong><small>{hud.spectate?'WATCHED':'HEALTH'}</small></div><div className="armor"><Shield size={22}/><strong>{Math.ceil(player.armor)}</strong><small>ARMOR</small></div><div className="health-track"><i style={{width:`${player.health}%`}}/></div></div>{!hud.spectate&&<div className={`ability-hud ${player.active>0?'active':''}`}><span className="ability-q">Q</span>{powerIcon(player.harness,25)}<div><strong>{activePower?.power}</strong><small>{hud.config.mode==='instagib'?'DISABLED IN INSTAGIB':player.active>0?`ACTIVE · ${player.active.toFixed(1)}s`:player.cooldown>0?`RECHARGING · ${player.cooldown.toFixed(1)}s`:'ABILITY READY'}</small></div><div className="cooldown-track"><i style={{width:`${100*(1-player.cooldown/((activePower?.cooldown||1)*(hud.config.fastPowers?.5:1)))}%`}}/></div></div>}{!hud.spectate&&<div className="weapon-hud"><div className="weapon-slots">{WEAPONS.map((w:any,i:number)=><span key={w.name} className={`${player.weapon===i?'equipped':''} ${player.ammo[i]===0?'unavailable':''}`}>{i+1} {w.short}</span>)}</div><div><strong>{player.ammo[player.weapon]}</strong><span>{WEAPONS[player.weapon].name}<small>{player.ammo[player.weapon]==='∞'?'UNLIMITED AMMO':'AMMUNITION'}</small></span></div></div>}</div>
 {hud.net&&<div className={`game-chat ${chatOpen?'open':''}`}>{chatOpen?<><div className="chat-lines">{chatLog.slice(-10).map((m:any,i:number)=><div key={i}><b>{m.name}</b>{m.text}</div>)}</div><input ref={chatInputRef} className="chat-input" autoFocus value={chatDraft} onChange={e=>setChatDraft(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')sendChat();else if(e.key==='Escape')setChatOpen(false);}} placeholder="MESSAGE · ENTER SENDS · ESC CLOSES" aria-label="Chat message" spellCheck={false}/></>:<><div className="chat-lines">{chatLog.slice(-4).map((m:any,i:number)=><div key={i}><b>{m.name}</b>{m.text}</div>)}</div><div className="chat-hint">T / ENTER · CHAT</div></>}</div>}
 <div className="hud-bottom-note"><span>TAB / SCOREBOARD</span>{display.showFps&&<span>{hud.fps||0} FPS · {hud.renderer==='software'?'CPU':'WEBGL'}</span>}<span>ESC / PAUSE</span></div></div>
 {scores&&mode==='playing'&&<div className="scores-overlay"><p className="eyebrow">LIVE STANDINGS</p>{scoreboard}</div>}
 </>}
 {mode==='paused'&&<div className="modal-backdrop"><section className="game-modal"><p className="eyebrow">SIMULATION PAUSED</p><h2>Take a breath.</h2><p>The arena will wait for you.</p><button className="deploy-button" onClick={resume}><span>RESUME MATCH</span><Play size={20}/></button>{prefs}<p className="pause-controls">WASD move · Space jump · Mouse fire<br/>1–5 / wheel weapons · Q power · Tab scores</p><button className="secondary-button" onClick={()=>{changeMode('selection');setHud(null);}}>RETURN TO LOADOUT</button></section></div>}
   {mode==='results'&&hud&&<div className="modal-backdrop"><section className="game-modal result-modal"><p className="eyebrow">MATCH COMPLETE / {clock(hud.time)}</p><h2>{hud.net?(hud.spectate?`${hud.leaders[0]} wins.`:hud.leaders.length>1?'Dead heat.':hud.leaders[0]===player?.name?'You own the arena.':`${hud.leaders[0]} wins.`):hud.config.botCount===0?'Practice complete.':hud.leaders.length>1?'Dead heat.':player?.frags===Math.max(...hud.actors.map((a:any)=>a.frags))?'You own the arena.':`${hud.leaders[0]} wins.`}</h2><p>{hud.net?(hud.leaders.length>1?`${hud.leaders.join(' & ')} tied for the lead.`:'The last token has been spent.'):hud.config.botCount===0?'Ready to add opponents? Return to loadout to change your match.':hud.leaders.length>1?`${hud.leaders.join(' & ')} tied for the lead.`:'The last token has been spent.'}</p>{scoreboard}{hud.net?runtime.current?.net?.isHost?<button className="deploy-button" onClick={()=>runtime.current?.net?.start()}><span>PLAY AGAIN</span><RotateCcw size={21}/></button>:<button className="deploy-button" disabled><span>WAITING FOR HOST</span><RotateCcw size={21}/></button>:<button className="deploy-button" onClick={start}><span>PLAY AGAIN</span><RotateCcw size={21}/></button>}{hud.net?<button className="secondary-button" onClick={disconnectNet}>LEAVE SERVER</button>:<button className="secondary-button" onClick={()=>{changeMode('selection');setHud(null);}}>CHANGE LOADOUT</button>}</section></div>}
 </main>;
}
