import test from 'node:test';
import assert from 'node:assert/strict';
import {Room,PLAYER_LIMIT} from './room.mjs';
function rng(){let n=11;return()=>((n=(Math.imul(n,1664525)+1013904223)>>>0)/4294967296);}
const find=(msgs,type,to)=>msgs.find(m=>m.msg.type===type&&(to===undefined||m.to===to))?.msg;
const last=(msgs,type)=>[...msgs].reverse().find(m=>m.msg.type===type)?.msg;
test('first joiner becomes host; Claude restriction and names are applied',()=>{
 const room=new Room('r',rng());
 room.join(1,'Alice','chatgpt','openclaw');
 room.join(2,'Bob','claude','hermes');
 room.join(3,'','unknown','hermes');
 const msgs=room.drain();
 assert.equal(find(msgs,'welcome',1).host,true);
 assert.equal(find(msgs,'welcome',2).host,false);
 const lobby=last(msgs,'lobby');
 assert.equal(lobby.hostId,1);
 assert.equal(lobby.players.length,3);
 assert.equal(lobby.players[1].name,'Bob');
 assert.equal(lobby.players[1].harness,'claudecode');
 assert.equal(lobby.players[2].name,'ChatGPT');
 assert.equal(lobby.players[2].character,'chatgpt');
 assert.equal(room.hostId,1);
});
test('host sets normalized config; non-host cannot host or start',()=>{
 const room=new Room('r',rng());
 room.join(1,'Host');room.join(2,'Peon');
 room.drain();
 room.host(2,{botCount:99,fragLimit:1},'bogus');
 let msgs=room.drain();
 assert.ok(find(msgs,'error',2));
 assert.equal(room.config,null);
 room.host(1,{botCount:2,fragLimit:5,timeLimit:60,damage:2},'crosswire');
 room.drain();
 assert.equal(room.config.botCount,2);
 assert.equal(room.config.fragLimit,5);
 assert.equal(room.config.damage,2);
 assert.equal(room.mapId,'crosswire');
 room.start(2);
 assert.ok(find(room.drain(),'error',2));
 assert.equal(room.match,null);
});
test('start creates a match with one actor per peer plus bots; actor ids and names align',()=>{
 const room=new Room('r',rng());
 room.join(1,'Alice');room.join(2,'Bob');
 room.host(1,{botCount:2,fragLimit:5,timeLimit:60},'crosswire');
 room.start(1);
 const msgs=room.drain();
 assert.equal(room.started,true);
 assert.equal(room.roundOver,false);
 assert.equal(room.match.actors.length,4);
 assert.equal(room.match.humanCount,2);
 assert.equal(room.match.actors[0].name,'Alice');
 assert.equal(room.match.actors[1].name,'Bob');
 assert.ok(room.match.actors[0].bot===null&&room.match.actors[1].bot===null);
 assert.ok(room.match.actors[2].bot&&room.match.actors[3].bot);
 const lobby=last(msgs,'lobby');
 assert.deepEqual(lobby.players.map(p=>p.actorId),[0,1]);
});
test('remote inputs drive look, fire and events stream back as deltas',()=>{
 const room=new Room('r',rng());
 room.join(1,'A');room.join(2,'B');
 room.host(1,{botCount:0,timeLimit:30},'crosswire');
 room.start(1);
 room.drain();
 const [a,b]=room.match.actors;
 Object.assign(a,{x:-9,y:0,z:8,protection:0,shotWait:0,yaw:0,pitch:0});
 Object.assign(b,{x:-9,y:0,z:-2,protection:0,shotWait:0,yaw:0,pitch:0});
 room.input(1,{yaw:0,fire:true});
 room.input(2,{yaw:Math.PI,fire:true});
 for(let i=0;i<4;i++)room.tick(1/60);
 const msgs=room.drain();
 assert.equal(a.health,89);
 assert.equal(b.health,89);
 assert.ok(Math.abs(b.yaw-Math.PI)<1e-9);
 const ev1=find(msgs,'events',1).items,ev2=find(msgs,'events',2).items;
 assert.ok(ev1.some(e=>e.type==='damage'&&e.actor===1&&e.source===0));
 assert.ok(ev2.some(e=>e.type==='damage'&&e.actor===0&&e.source===1));
 assert.ok(find(msgs,'snapshot').state.actors[1].health===89);
 assert.ok(find(msgs,'snapshot').state.actors[0].health===89);
});
test('start and rematch preserve every human validated loadout',()=>{
 const room=new Room('r',rng());
 room.join(1,'Alice','kimi','hermes');
 room.join(2,'Watcher','chatgpt','openclaw','',true);
 room.join(3,'Bob','claude','hermes');
 room.join(4,'Carol','invalid','invalid');
 room.host(1,{botCount:1},'crosswire');
 const expected=[['Alice','kimi','hermes'],['Bob','claude','claudecode'],['Carol','chatgpt','openclaw']];
 for(let round=0;round<2;round++){
  room.drain();
  room.start(1);
  assert.deepEqual(room.match.actors.slice(0,3).map(a=>[a.name,a.character,a.harness]),expected);
  assert.ok(room.match.actors.slice(0,3).every(a=>a.bot===null));
  assert.ok(room.match.actors[3].bot);
  const msgs=room.drain();
  assert.ok(msgs.findIndex(m=>m.msg.type==='lobby')<msgs.findIndex(m=>m.msg.type==='start'));
  room.match.over=true;
  room.tick(1/60);
  assert.equal(room.roundOver,true);
 }
});
test('match completes on the timer and results broadcast once with final events delivered',()=>{
 const room=new Room('r',rng());
 room.join(1,'A');room.join(2,'B');
 room.host(1,{botCount:0,fragLimit:5,timeLimit:60,respawn:1},'crosswire');
 room.start(1);
 room.drain();
 const [a,b]=room.match.actors;
 Object.assign(a,{x:-10,y:0,z:3.3,weapon:1,ammo:[Infinity,1,0,0,0],protection:0,shotWait:0,yaw:0,pitch:0});
 Object.assign(b,{x:-10,y:0,z:-3.3,protection:0,health:40});
 room.input(1,{yaw:0,fire:true});
 for(let i=0;i<3700&&!room.roundOver;i++)room.tick(1/60);
 const msgs=room.drain();
 assert.equal(room.roundOver,true);
 assert.equal(room.match.over,true);
 assert.equal(a.frags,1);
 assert.equal(msgs[msgs.length-1].msg.type,'results');
 assert.equal(msgs[msgs.length-1].msg.state.over,true);
 const ev=msgs.filter(m=>m.msg.type==='events'&&m.to===1).flatMap(m=>m.msg.items);
 assert.ok(ev.some(e=>e.type==='death'));
 assert.ok(ev.some(e=>e.type==='damage'&&e.source===0));
});
test('leave mid-match hands the seat to a bot; pre-start leave frees the slot',()=>{
 const room=new Room('r',rng());
 room.join(1,'A');room.join(2,'B');
 room.host(1,{botCount:0,timeLimit:30},'crosswire');
 room.start(1);
 room.drain();
 const [a,b]=room.match.actors;
 Object.assign(b,{x:-9,y:0,z:0,protection:0});
 room.input(2,{x:1,z:1});
 room.leave(2);
 let moved=false;
 for(let i=0;i<240;i++){room.tick(1/60);if(Math.hypot(b.x+9,b.z)>1)moved=true;}
 assert.ok(b.bot,'seat is handed to a bot');
 assert.ok(moved,'bot takes over the vacated seat');
 assert.equal(room.peers.size,1);
 assert.equal(room.hostId,1);
 room2: {
  const r=new Room('r2',rng());
  r.join(1,'A');r.join(2,'B');
  r.leave(1);
  r.host(2,{botCount:0},'crosswire');
  r.start(2);
  assert.equal(r.match.actors.length,1);
  assert.equal(r.match.actors[0].name,'B');
  assert.equal(r.hostId,2);
 }
});
test('jump and power arrive as one-shot edges while fire stays level',()=>{
 const room=new Room('r',rng());
 room.join(1,'A');
 room.host(1,{botCount:0,timeLimit:30},'crosswire');
 room.start(1);
 room.drain();
 const [a]=room.match.actors;
 Object.assign(a,{x:0,y:0,z:0,protection:0,shotWait:0,health:100});
 room.input(1,{jump:true});
 room.input(1,{jump:true});
 room.tick(1/60);
 assert.ok(a.vy>0,'first edge should jump');
 const vy1=a.vy;
 for(let i=0;i<10;i++)room.tick(1/60);
 assert.ok(a.vy<=vy1,'repeated held edge must not re-jump');
 a.health=100;a.cooldown=0;
 room.input(1,{power:true});
 room.input(1,{power:true});
 room.tick(1/60);
 assert.equal(room.match.stats.powers,1);
 assert.ok(a.cooldown>0);
 const shots=a.shots;
  for(let i=0;i<20;i++)room.tick(1/60);
  assert.equal(room.match.stats.powers,1,'power edge consumed exactly once');
});
test('disconnect holds the seat; token reattach restores mid-match play',()=>{
 const room=new Room('r',rng(),{graceMs:60000});
 room.join(1,'A');room.join(2,'B');
 const msgs=room.drain();
 const tokenB=find(msgs,'welcome',2).token;
 room.host(1,{botCount:0,timeLimit:60},'crosswire');
 room.start(1);
 room.drain();
 assert.equal(room.match.actors[1].name,'B');
 room.disconnect(2);
 let lobby=last(room.drain(),'lobby');
 assert.equal(lobby.players.length,2);
 assert.equal(lobby.players[1].connected,false);
 room.join(3,'ignored','chatgpt','openclaw',tokenB);
 const m=room.drain();
 assert.equal(find(m,'welcome',3).reconnected,true);
 lobby=last(m,'lobby');
 assert.equal(lobby.players.length,2);
 assert.equal(lobby.players[1].name,'B');
 assert.equal(lobby.players[1].actorId,1);
 room.input(3,{yaw:0,fire:true});
 for(let i=0;i<30;i++)room.tick(1/60);
 const ev=room.drain().filter(x=>x.msg.type==='events').flatMap(x=>x.msg.items);
 assert.ok(ev.some(e=>e.type==='shot'&&e.actor===1));
});
test('grace expiry converts the seat to a bot and migrates the host',()=>{
 const room=new Room('r',rng(),{graceMs:1000});
 room.join(1,'Host');room.join(2,'B');
 const msgs=room.drain();
 const token1=find(msgs,'welcome',1).token;
 room.host(1,{botCount:0,timeLimit:60},'crosswire');
 room.start(1);
 room.drain();
 assert.equal(room.match.actors[0].bot,null);
 room.disconnect(1);
 assert.equal(room.hostId,1,'host stays reserved during grace');
 room.expireGrace(Date.now()+5000);
 assert.equal(room.hostId,2,'host migrates after grace');
 assert.ok(room.match.actors[0].bot,'seat becomes a bot');
 assert.ok(room.match.actors[0].name.endsWith('· BOT'));
 room.join(3,'','','',token1);
 const m=room.drain();
 assert.equal(find(m,'welcome',3)?.reconnected,undefined,'expired token reattaches nothing');
 assert.equal(find(m,'welcome',3)?.token===token1,false,'expired token gets a fresh session');
 assert.equal(last(m,'lobby').players.length,2,'rejoin creates a fresh seat');
});
test('explicit leave mid-match converts the seat to a bot immediately',()=>{
 const room=new Room('r',rng(),{graceMs:60000});
 room.join(1,'A');room.join(2,'B');
 room.host(1,{botCount:0,timeLimit:60},'crosswire');
 room.start(1);
 room.drain();
 room.leave(2);
 assert.ok(room.match.actors[1].bot);
 assert.equal(room.match.actors[1].name,'B · BOT');
 assert.equal(room.peers.size,1);
 assert.equal(room.hostId,1);
});
test('disconnected host who reconnects inside grace stays host; play resumes',()=>{
 const room=new Room('r',rng(),{graceMs:60000});
 room.join(1,'Host');room.join(2,'B');
 const msgs=room.drain();
 const token1=find(msgs,'welcome',1).token;
 room.host(1,{botCount:0,timeLimit:60},'crosswire');
 room.start(1);
 room.drain();
 room.disconnect(1);
 room.join(3,'','','',token1);
 const m=room.drain();
 assert.equal(find(m,'welcome',3).reconnected,true);
 assert.equal(room.hostId,3,'reconnected host keeps the host role');
 assert.equal(room.match.actors[0].bot,null,'seat was never converted');
 room.input(3,{yaw:0,fire:true});
 for(let i=0;i<30;i++)room.tick(1/60);
 assert.ok(room.match.actors[0].shots>0,'inputs flow again after reattach');
});
test('start can rematch after a completed round; inputs ignored while round over',()=>{
 const room=new Room('r',rng());
 room.join(1,'A');room.join(2,'B');
 room.host(1,{botCount:0,fragLimit:5,timeLimit:60,respawn:1},'crosswire');
 room.start(1);
 room.drain();
 const [a,b]=room.match.actors;
 Object.assign(a,{x:-10,y:0,z:3.3,weapon:1,ammo:[Infinity,1,0,0,0],protection:0,shotWait:0,yaw:0});
 Object.assign(b,{x:-10,y:0,z:-3.3,protection:0,health:40});
 room.input(1,{yaw:0,fire:true});
 for(let i=0;i<3700&&!room.roundOver;i++)room.tick(1/60);
 room.drain();
 room.input(1,{fire:true});
 const m1=room.match;
 room.start(1);
 assert.notEqual(room.match,m1);
 assert.equal(room.roundOver,false);
 assert.equal(room.match.actors[0].health,100);
 assert.equal(room.match.actors[0].frags,0);
 assert.ok(find(room.drain(),'start'));
});
